import SectionImage from '../components/SectionImage'

export default function Appendix() {
  return (
    <div className="page-enter-active">
      <SectionImage
        prompt="An organized quick reference study guide spread on a wooden desk, herbal medicine ingredients arranged neatly, scrolls and notes, warm ambient lighting, scholarly atmosphere, clean educational composition"
        alt="附录速查"
      />

      <div className="content-section">

        <section id="sec-app-1">
          <h2>一、全书速记总表</h2>

          <p>
            本书所有核心要素汇总如下。掌握这张表，就等于掌握了辨证思维的全部"零件"。
          </p>

          <h3>🏠 15个房间（病位）</h3>
          <table>
            <thead>
              <tr>
                <th>类别</th>
                <th>名称</th>
                <th>功能要点</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={5}>五脏</td>
                <td>心</td>
                <td>主血脉、藏神</td>
              </tr>
              <tr>
                <td>肝</td>
                <td>主疏泄、藏血</td>
              </tr>
              <tr>
                <td>脾</td>
                <td>主运化、统血</td>
              </tr>
              <tr>
                <td>肺</td>
                <td>主气、司呼吸、宣发肃降</td>
              </tr>
              <tr>
                <td>肾</td>
                <td>藏精、主水、纳气</td>
              </tr>
              <tr>
                <td rowSpan={6}>六腑</td>
                <td>胆</td>
                <td>贮藏和排泄胆汁，主决断</td>
              </tr>
              <tr>
                <td>胃</td>
                <td>受纳、腐熟水谷</td>
              </tr>
              <tr>
                <td>小肠</td>
                <td>泌别清浊</td>
              </tr>
              <tr>
                <td>大肠</td>
                <td>传化糟粕</td>
              </tr>
              <tr>
                <td>膀胱</td>
                <td>贮尿和排尿</td>
              </tr>
              <tr>
                <td>三焦</td>
                <td>通行元气、运行水液</td>
              </tr>
              <tr>
                <td rowSpan={4}>层次</td>
                <td>卫分</td>
                <td>最表层，主防御</td>
              </tr>
              <tr>
                <td>气分</td>
                <td>较深层，主气化</td>
              </tr>
              <tr>
                <td>营分</td>
                <td>更深层，主营养</td>
              </tr>
              <tr>
                <td>血分</td>
                <td>最深层，主血液</td>
              </tr>
            </tbody>
          </table>

          <h3>💎 5种宝贝（气血津液精）</h3>
          <table>
            <thead>
              <tr>
                <th>宝贝</th>
                <th>性质</th>
                <th>功能</th>
                <th>异常表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>气</td>
                <td>无形、主动</td>
                <td>推动、温煦、防御、固摄、气化</td>
                <td>气虚、气滞、气逆、气陷、气脱</td>
              </tr>
              <tr>
                <td>血</td>
                <td>有形、主濡养</td>
                <td>营养全身、载气</td>
                <td>血虚、血瘀、血热、出血</td>
              </tr>
              <tr>
                <td>津</td>
                <td>清稀、主表</td>
                <td>滋润肌肤、孔窍</td>
                <td>津亏、痰饮、湿困</td>
              </tr>
              <tr>
                <td>液</td>
                <td>稠厚、主里</td>
                <td>濡养关节、脑髓、脏腑</td>
                <td>液亏、痰浊</td>
              </tr>
              <tr>
                <td>精</td>
                <td>最精微、主根本</td>
                <td>生长发育、生殖、抗衰</td>
                <td>精虚、精亏、精关不固</td>
              </tr>
            </tbody>
          </table>

          <h3>⚠️ 10种毛病（状态异常）</h3>
          <table>
            <thead>
              <tr>
                <th>分类</th>
                <th>毛病</th>
                <th>含义</th>
                <th>核心表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={4}>6虚</td>
                <td>气虚</td>
                <td>气不够用</td>
                <td>乏力、气短、自汗、舌淡、脉虚</td>
              </tr>
              <tr>
                <td>血虚</td>
                <td>血不够用</td>
                <td>面色苍白、头晕、心悸、舌淡、脉细</td>
              </tr>
              <tr>
                <td>阴虚</td>
                <td>阴液不足</td>
                <td>五心烦热、口干、盗汗、舌红少苔、脉细数</td>
              </tr>
              <tr>
                <td>阳虚</td>
                <td>阳气不足</td>
                <td>畏寒肢冷、腰膝酸软、舌淡胖、脉沉迟</td>
              </tr>
              <tr>
                <td rowSpan={2}>滞瘀停</td>
                <td>滞</td>
                <td>运行不畅</td>
                <td>胀痛、窜痛、时轻时重</td>
              </tr>
              <tr>
                <td>瘀/停</td>
                <td>停滞凝聚</td>
                <td>刺痛固定、痰多、水肿、舌紫暗</td>
              </tr>
              <tr>
                <td rowSpan={3}>逆陷脱</td>
                <td>逆</td>
                <td>方向反了</td>
                <td>咳嗽、呕叶、呃逆、气上冲</td>
              </tr>
              <tr>
                <td>陷</td>
                <td>往下掉</td>
                <td>脱肛、胃下垂、子宫脱垂</td>
              </tr>
              <tr>
                <td>脱</td>
                <td>收不住</td>
                <td>大汗淋漓、遗精、崩漏、滑胎</td>
              </tr>
              <tr>
                <td rowSpan={2}>寒热</td>
                <td>寒</td>
                <td>温度偏低</td>
                <td>畏寒、喜暖、肢冷、便溏</td>
              </tr>
              <tr>
                <td>热</td>
                <td>温度偏高</td>
                <td>发热、喜凉、面红、便秘</td>
              </tr>
            </tbody>
          </table>

          <h3>🔍 17个坏蛋（病因）</h3>
          <table>
            <thead>
              <tr>
                <th>分类</th>
                <th>坏蛋</th>
                <th>特点</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={6}>六淫</td>
                <td>风</td>
                <td>善行数变，轻扬开泄，百病之长</td>
              </tr>
              <tr>
                <td>寒</td>
                <td>凝滞收引，易伤阳气</td>
              </tr>
              <tr>
                <td>暑</td>
                <td>炎热升散，耗气伤津，多夹湿</td>
              </tr>
              <tr>
                <td>湿</td>
                <td>重浊黏滞，阻遏气机，易伤脾阳</td>
              </tr>
              <tr>
                <td>燥</td>
                <td>干涩伤津，易伤肺</td>
              </tr>
              <tr>
                <td>火</td>
                <td>炎热燔灼，耗气伤津，生风动血</td>
              </tr>
              <tr>
                <td rowSpan={5}>内邪</td>
                <td>痰饮</td>
                <td>水液代谢障碍，随气升降，无处不到</td>
              </tr>
              <tr>
                <td>瘀血</td>
                <td>血行不畅或离经之血，刺痛固定</td>
              </tr>
              <tr>
                <td>结石</td>
                <td>湿热浊邪煎熬而成，阻滞气机</td>
              </tr>
              <tr>
                <td>积食</td>
                <td>饮食停滞，脘腹胀满</td>
              </tr>
              <tr>
                <td>虫积</td>
                <td>寄生虫感染，腹痛、面黄肌瘦</td>
              </tr>
              <tr>
                <td rowSpan={6}>七情<br/>（去重叠）</td>
                <td>喜</td>
                <td>过喜伤心，气缓</td>
              </tr>
              <tr>
                <td>怒</td>
                <td>过怒伤肝，气上</td>
              </tr>
              <tr>
                <td>忧</td>
                <td>过忧伤肺，气聚</td>
              </tr>
              <tr>
                <td>思</td>
                <td>过思伤脾，气结</td>
              </tr>
              <tr>
                <td>悲</td>
                <td>过悲伤肺，气消</td>
              </tr>
              <tr>
                <td>恐</td>
                <td>过恐伤肾，气下</td>
              </tr>
            </tbody>
          </table>

          <h3>🧮 万能公式</h3>
          <blockquote>
            <p><strong>证候 = 坏蛋 × 毛病 × 宝贝 × 房间</strong></p>
          </blockquote>
          <p>
            即：<strong>证候 = 病因 × 状态 × 气血津液精 × 病位</strong>
          </p>
          <p>
            组合示例：
          </p>
          <ul>
            <li>风寒（坏蛋）+ 肺（房间）= 风寒束肺证</li>
            <li>寒（坏蛋）+ 凝滞（毛病）+ 血（宝贝）+ 胞宫（房间）= 寒凝血瘀证</li>
            <li>火（坏蛋）+ 热（毛病）+ 气（宝贝）+ 肝（房间）= 肝火炽盛证</li>
            <li>气虚（毛病）+ 陷（毛病）+ 气（宝贝）+ 脾（房间）= 中气下陷证</li>
            <li>湿（坏蛋）+ 困（毛病）+ 脾（房间）= 湿困脾胃证</li>
            <li>怒（坏蛋）+ 郁结（毛病）+ 气（宝贝）+ 肝（房间）= 肝气郁结证</li>
          </ul>
        </section>

        <section id="sec-app-2">
          <h2>二、辨证口诀</h2>

          <h3>核心口诀</h3>
          <blockquote>
            <p><strong>哪屋哪物啥原因，是虚是实还是堵？</strong></p>
          </blockquote>
          <p>
            这句话概括了辨证的全部关键：
          </p>
          <ul>
            <li><strong>哪屋</strong>——问题在哪个房间？（病位：心肝脾肺肾……）</li>
            <li><strong>哪物</strong>——什么物资出问题了？（气血津液精）</li>
            <li><strong>啥原因</strong>——是谁搞的破坏？（六淫、内邪、七情）</li>
            <li><strong>是虚是实还是堵</strong>——属于哪种状态异常？（虚证、实证、虚实夹杂）</li>
          </ul>

          <h3>扩展口诀</h3>
          <blockquote>
            <p><strong>房间要找准，宝贝要分清。</strong></p>
            <p><strong>毛病看状态，坏蛋追病因。</strong></p>
            <p><strong>虚则补其母，实则泻其子。</strong></p>
            <p><strong>寒者热之治，热者寒之平。</strong></p>
          </blockquote>
          <ul>
            <li><strong>房间要找准</strong>——症状出现在哪个脏腑？头痛部位不同，涉及的经络脏腑也不同</li>
            <li><strong>宝贝要分清</strong>——是气的问题还是血的问题？是津液还是精？</li>
            <li><strong>毛病看状态</strong>——是虚了、堵了、还是方向反了？是寒了还是热了？</li>
            <li><strong>坏蛋追病因</strong>——是外感六淫还是内伤七情？是饮食不当还是劳倦过度？</li>
          </ul>

          <h3>治法口诀</h3>
          <blockquote>
            <p><strong>虚补实泻寒温热清，</strong></p>
            <p><strong>滞行瘀消逆降陷升。</strong></p>
            <p><strong>痰化湿燥饮逐水，</strong></p>
            <p><strong>风祛寒散火当清。</strong></p>
          </blockquote>
          <ul>
            <li>虚证用补法，实证用泻法，寒证用温热，热证用寒凉</li>
            <li>气滞行气，瘀血化瘀，气逆降气，气陷升提</li>
            <li>痰证化痰，湿证燥湿，饮证逐饮</li>
            <li>风证祛风，寒证散寒，火证清热</li>
          </ul>
        </section>

        <section id="sec-app-3">
          <h2>三、常见证候生成链全表</h2>

          <p>
            以下表格展示了常见证候的标准拆解，帮助你理解每一个证候是如何由"坏蛋 × 毛病 × 宝贝 × 房间"组合而成的。
          </p>

          <h3>外感证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>风寒束表</td>
                <td>风寒</td>
                <td>寒、滞</td>
                <td>卫气</td>
                <td>卫分</td>
                <td>辛温解表</td>
              </tr>
              <tr>
                <td>风热犯卫</td>
                <td>风热</td>
                <td>热</td>
                <td>卫气</td>
                <td>卫分</td>
                <td>辛凉解表</td>
              </tr>
              <tr>
                <td>暑湿袭表</td>
                <td>暑湿</td>
                <td>湿、热</td>
                <td>卫气、津</td>
                <td>卫分、脾</td>
                <td>清暑化湿解表</td>
              </tr>
              <tr>
                <td>风热犯肺</td>
                <td>风热</td>
                <td>热、逆</td>
                <td>气</td>
                <td>肺</td>
                <td>疏风清热、宣肺止咳</td>
              </tr>
              <tr>
                <td>风寒束肺</td>
                <td>风寒</td>
                <td>寒、滞</td>
                <td>气</td>
                <td>肺</td>
                <td>疏风散寒、宣肺止咳</td>
              </tr>
              <tr>
                <td>燥邪伤肺</td>
                <td>燥</td>
                <td>燥</td>
                <td>津、液</td>
                <td>肺</td>
                <td>清肺润燥</td>
              </tr>
            </tbody>
          </table>

          <h3>心系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>心气虚</td>
                <td>—</td>
                <td>气虚</td>
                <td>气</td>
                <td>心</td>
                <td>补益心气</td>
              </tr>
              <tr>
                <td>心血虚</td>
                <td>—</td>
                <td>血虚</td>
                <td>血</td>
                <td>心</td>
                <td>养血安神</td>
              </tr>
              <tr>
                <td>心阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液</td>
                <td>心</td>
                <td>滋阴养心</td>
              </tr>
              <tr>
                <td>心阳虚</td>
                <td>—</td>
                <td>阳虚</td>
                <td>阳气</td>
                <td>心</td>
                <td>温通心阳</td>
              </tr>
              <tr>
                <td>心火亢盛</td>
                <td>火</td>
                <td>热</td>
                <td>气、血</td>
                <td>心</td>
                <td>清心泻火</td>
              </tr>
              <tr>
                <td>痰蒙心窍</td>
                <td>痰饮</td>
                <td>痰、滞</td>
                <td>津</td>
                <td>心</td>
                <td>化痰开窍</td>
              </tr>
            </tbody>
          </table>

          <h3>肝系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>肝气郁结</td>
                <td>怒、思</td>
                <td>滞</td>
                <td>气</td>
                <td>肝</td>
                <td>疏肝理气</td>
              </tr>
              <tr>
                <td>肝火上炎</td>
                <td>火、怒</td>
                <td>热、逆</td>
                <td>气、血</td>
                <td>肝</td>
                <td>清肝泻火</td>
              </tr>
              <tr>
                <td>肝阳上亢</td>
                <td>—</td>
                <td>阴虚、逆</td>
                <td>阴、气</td>
                <td>肝、肾</td>
                <td>平肝潜阳</td>
              </tr>
              <tr>
                <td>肝血虚</td>
                <td>—</td>
                <td>血虚</td>
                <td>血</td>
                <td>肝</td>
                <td>养血柔肝</td>
              </tr>
              <tr>
                <td>肝阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液</td>
                <td>肝</td>
                <td>滋阴养肝</td>
              </tr>
              <tr>
                <td>肝气犯胃</td>
                <td>怒</td>
                <td>滞、逆</td>
                <td>气</td>
                <td>肝、胃</td>
                <td>疏肝和胃</td>
              </tr>
              <tr>
                <td>寒滞肝脉</td>
                <td>寒</td>
                <td>寒、滞</td>
                <td>气、血</td>
                <td>肝</td>
                <td>暖肝散寒</td>
              </tr>
            </tbody>
          </table>

          <h3>脾系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>脾气虚</td>
                <td>—</td>
                <td>气虚</td>
                <td>气</td>
                <td>脾</td>
                <td>补脾益气</td>
              </tr>
              <tr>
                <td>脾阳虚</td>
                <td>—</td>
                <td>阳虚、寒</td>
                <td>阳气</td>
                <td>脾</td>
                <td>温补脾阳</td>
              </tr>
              <tr>
                <td>中气下陷</td>
                <td>—</td>
                <td>气虚、陷</td>
                <td>气</td>
                <td>脾</td>
                <td>补中益气、升阳举陷</td>
              </tr>
              <tr>
                <td>脾不统血</td>
                <td>—</td>
                <td>气虚、脱</td>
                <td>气、血</td>
                <td>脾</td>
                <td>补脾摄血</td>
              </tr>
              <tr>
                <td>湿困脾胃</td>
                <td>湿</td>
                <td>湿、滞</td>
                <td>津、气</td>
                <td>脾、胃</td>
                <td>化湿和中</td>
              </tr>
              <tr>
                <td>寒湿困脾</td>
                <td>寒、湿</td>
                <td>寒、湿、滞</td>
                <td>津、气</td>
                <td>脾</td>
                <td>温中化湿</td>
              </tr>
            </tbody>
          </table>

          <h3>胃系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>胃热炽盛</td>
                <td>火、积食</td>
                <td>热、逆</td>
                <td>气、津</td>
                <td>胃</td>
                <td>清胃泻火</td>
              </tr>
              <tr>
                <td>胃阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液</td>
                <td>胃</td>
                <td>益胃生津</td>
              </tr>
              <tr>
                <td>胃寒</td>
                <td>寒</td>
                <td>寒、滞</td>
                <td>气</td>
                <td>胃</td>
                <td>温胃散寒</td>
              </tr>
              <tr>
                <td>食滞胃脘</td>
                <td>积食</td>
                <td>滞、逆</td>
                <td>气</td>
                <td>胃</td>
                <td>消食导滞</td>
              </tr>
            </tbody>
          </table>

          <h3>肺系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>肺气虚</td>
                <td>—</td>
                <td>气虚</td>
                <td>气</td>
                <td>肺</td>
                <td>补益肺气</td>
              </tr>
              <tr>
                <td>肺阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液</td>
                <td>肺</td>
                <td>滋阴润肺</td>
              </tr>
              <tr>
                <td>风寒束肺</td>
                <td>风寒</td>
                <td>寒、滞、逆</td>
                <td>气</td>
                <td>肺</td>
                <td>疏风散寒、宣肺止咳</td>
              </tr>
              <tr>
                <td>风热犯肺</td>
                <td>风热</td>
                <td>热、逆</td>
                <td>气、津</td>
                <td>肺</td>
                <td>疏风清热、宣肺止咳</td>
              </tr>
              <tr>
                <td>痰热壅肺</td>
                <td>痰饮、火</td>
                <td>痰、热、逆</td>
                <td>津、气</td>
                <td>肺</td>
                <td>清热化痰、肃肺止咳</td>
              </tr>
            </tbody>
          </table>

          <h3>肾系证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>肾阳虚</td>
                <td>—</td>
                <td>阳虚、寒</td>
                <td>阳气</td>
                <td>肾</td>
                <td>温补肾阳</td>
              </tr>
              <tr>
                <td>肾阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液、精</td>
                <td>肾</td>
                <td>滋补肾阴</td>
              </tr>
              <tr>
                <td>肾精不足</td>
                <td>—</td>
                <td>精虚</td>
                <td>精</td>
                <td>肾</td>
                <td>补肾填精</td>
              </tr>
              <tr>
                <td>肾气不固</td>
                <td>—</td>
                <td>气虚、脱</td>
                <td>气、精</td>
                <td>肾</td>
                <td>补肾固摄</td>
              </tr>
              <tr>
                <td>肾不纳气</td>
                <td>—</td>
                <td>气虚、逆</td>
                <td>气</td>
                <td>肾、肺</td>
                <td>补肾纳气</td>
              </tr>
            </tbody>
          </table>

          <h3>复合证候</h3>
          <table>
            <thead>
              <tr>
                <th>证候名</th>
                <th>坏蛋</th>
                <th>毛病</th>
                <th>宝贝</th>
                <th>房间</th>
                <th>治法</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>心脾两虚</td>
                <td>—</td>
                <td>气虚、血虚</td>
                <td>气、血</td>
                <td>心、脾</td>
                <td>补益心脾、益气养血</td>
              </tr>
              <tr>
                <td>心肾不交</td>
                <td>—</td>
                <td>阴虚、热</td>
                <td>阴、气</td>
                <td>心、肾</td>
                <td>滋阴降火、交通心肾</td>
              </tr>
              <tr>
                <td>肝脾不和</td>
                <td>怒、思</td>
                <td>滞、气虚</td>
                <td>气</td>
                <td>肝、脾</td>
                <td>疏肝健脾</td>
              </tr>
              <tr>
                <td>肺肾阴虚</td>
                <td>—</td>
                <td>阴虚</td>
                <td>阴液</td>
                <td>肺、肾</td>
                <td>滋补肺肾</td>
              </tr>
              <tr>
                <td>气滞血瘀</td>
                <td>怒</td>
                <td>滞、瘀</td>
                <td>气、血</td>
                <td>肝、心</td>
                <td>行气活血</td>
              </tr>
              <tr>
                <td>气虚血瘀</td>
                <td>—</td>
                <td>气虚、瘀</td>
                <td>气、血</td>
                <td>心、脾</td>
                <td>益气活血</td>
              </tr>
              <tr>
                <td>阴虚火旺</td>
                <td>火</td>
                <td>阴虚、热</td>
                <td>阴、气</td>
                <td>肾、肝</td>
                <td>滋阴降火</td>
              </tr>
              <tr>
                <td>气阴两虚</td>
                <td>—</td>
                <td>气虚、阴虚</td>
                <td>气、阴液</td>
                <td>肺、肾、脾</td>
                <td>益气养阴</td>
              </tr>
              <tr>
                <td>痰瘀互结</td>
                <td>痰饮</td>
                <td>痰、瘀</td>
                <td>津、血</td>
                <td>随病位而定</td>
                <td>化痰祛瘀</td>
              </tr>
              <tr>
                <td>寒热错杂</td>
                <td>寒、火</td>
                <td>寒、热</td>
                <td>气、津</td>
                <td>脾胃</td>
                <td>寒热并用、调和脾胃</td>
              </tr>
            </tbody>
          </table>
        </section>

        <section id="sec-app-4">
          <h2>四、学习路线图</h2>

          <h3>学习路径建议</h3>
          <p>
            辨证思维的学习不需要死记硬背，按照以下路线循序渐迸，事半功倍：
          </p>

          <table>
            <thead>
              <tr>
                <th>阶段</th>
                <th>内容</th>
                <th>目标</th>
                <th>建议时间</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>第一阶段</td>
                <td>绪论 + 模块一（病位）</td>
                <td>认识身体的15个"房间"，了解每个房间的功能和异常信号</td>
                <td>3-5天</td>
              </tr>
              <tr>
                <td>第二阶段</td>
                <td>模块二（气血津液精）</td>
                <td>认识5种"宝贝"，理解它们的性质和异常表现</td>
                <td>2-3天</td>
              </tr>
              <tr>
                <td>第三阶段</td>
                <td>模块三（状态异常）</td>
                <td>掌握10种"毛病"，学会判断虚、实、寒、热</td>
                <td>3-4天</td>
              </tr>
              <tr>
                <td>第四阶段</td>
                <td>模块四（病因）</td>
                <td>认识17个"坏蛋"，学会追查病因</td>
                <td>2-3天</td>
              </tr>
              <tr>
                <td>第五阶段</td>
                <td>模块五（破案公式）</td>
                <td>学会用万能公式组合生成证候，能拆解常见证候</td>
                <td>3-4天</td>
              </tr>
              <tr>
                <td>第六阶段</td>
                <td>模块六（辨证实战）</td>
                <td>掌握五步辨证法，能独立分析常见病</td>
                <td>5-7天</td>
              </tr>
            </tbody>
          </table>

          <h3>学习技巧</h3>
          <ul>
            <li><strong>先框架后细节</strong>：不要一开始就钻细节，先建立整体框架，知道每个模块是什么、有什么用</li>
            <li><strong>多用类比</strong>：把"房间、宝贝、毛病、坏蛋"的比喻用到生活中，帮助理解抽象概念</li>
            <li><strong>做组合练习</strong>：随时用万能公式组合证候，看到什么症状就试着拆解</li>
            <li><strong>反复回看附录</strong>：遇到忘记的概念，随时回来看速记总表</li>
            <li><strong>边学边练</strong>：学完一个模块就做后面的练习题，不要等到全部学完再练</li>
          </ul>

          <h3>推荐学习顺序</h3>
          <ol>
            <li>先读绪论，了解辨证是什么、为什么学、怎么学</li>
            <li>按顺序学习模块一到模块四，打好基础</li>
            <li>学习模块五，掌握万能公式和证候生成</li>
            <li>进入模块六实战，先用五步法分析简单病例</li>
            <li>逐步增加难度，尝试分析复杂病例</li>
            <li>最后，用附录做复习和速查</li>
          </ol>
        </section>

        <section id="sec-app-5">
          <h2>五、辨证心法</h2>

          <h3>心法一：整体观念</h3>
          <p>
            人体是一个整体，不能头痛医头、脚痛医脚。一个地方出问题，往往与其他地方有关。比如：
          </p>
          <ul>
            <li>眼睛干涩——不只是眼睛的问题，可能是肝血不足（肝开窍于目）</li>
            <li>耳鸣——不只是耳朵的问题，可能是肾虚（肾开窍于耳）</li>
            <li>失眠——不只是睡不着的问题，可能是心肾不交、心脾两虚或肝火扰心</li>
          </ul>
          <p>
            辨证时要有全局观，把身体看作一个相互联系的系统，而不是孤立的零件。
          </p>

          <h3>心法二：抓主要矛盾</h3>
          <p>
            病人身上往往同时存在多种问题：既有气虚，又有血瘀，还有湿气。但我们要抓住最核心的问题——主要矛盾。
          </p>
          <p>
            主要矛盾的判断标准：
          </p>
          <ul>
            <li>哪个问题最痛苦？（以病人的主诉为准）</li>
            <li>哪个问题是根源？（解决它，其他问题可能随之缓解）</li>
            <li>哪个问题最紧急？（急则治其标，缓则治其本）</li>
          </ul>
          <p>
            比如一个病人既有气虚乏力多年，又突然感冒发烧。此时主要矛盾是感冒（标），而不是气虚（本）。先治感冒，再补气。
          </p>

          <h3>心法三：同病异治，异病同治</h3>
          <p>
            同样是感冒，风寒用辛温解表，风热用辛凉解表，暑湿用清暑化湿。这是<strong>同病异治</strong>——病相同，证不同，治法不同。
          </p>
          <p>
            反过来，不同的病，如果证候相同，可以用相同的治法。比如脱肛、胃下垂、子宫脱垂，三个不同的病，但都是"中气下陷证"，都可以用补中益气汤。这是<strong>异病同治</strong>。
          </p>
          <p>
            抓住证候的本质，超越病名的表象，是辨证思维的高级境界。
          </p>

          <h3>心法四：动态观察</h3>
          <p>
            证候不是一成不变的。一个病人今天可能是风寒束表，明天可能入里化热变成风热犯肺，后天可能热伤津液变成肺阴虚。
          </p>
          <p>
            所以辨证不是一锤子买卖，而是要动态观察、随证治之。这也是为什么中医强调"复诊"——病情在变，治法也要变。
          </p>

          <h3>心法五：以人为本</h3>
          <p>
            辨证辨的不是"病"，而是"人"。同一个人身上，不同时期、不同状态下，证候可能完全不同。不同的人得了同一种病，因为体质、年龄、性别、生活习惯不同，证候也可能完全不同。
          </p>
          <p>
            所以辨证要关注的是——<strong>这个人现在出了什么问题</strong>，而不是<strong>这个人得了什么病</strong>。
          </p>

          <h3>心法六：大道至简</h3>
          <p>
            辨证看起来很复杂：15个房间、5种宝贝、10种毛病、17个坏蛋，组合起来成千上万。但万变不离其宗，核心就是：
          </p>
          <blockquote>
            <p><strong>在哪儿？是什么？怎么了？谁干的？怎么办？</strong></p>
          </blockquote>
          <p>
            问清楚这五个问题，辨证就完成了。所有的知识都是为这五个问题服务的工具，不要被工具淹没，要记住你的目标——<strong>找到问题的根源</strong>。
          </p>
        </section>

        <section id="sec-app-6">
          <h2>六、常见误区</h2>

          <h3>误区一：对号入座</h3>
          <p>
            看到几个症状和某个证候描述一样，就马上断定是这个证候。比如看到"咳嗽、痰黄、咽痛"就断定是风热犯肺——但万一病人还有"怕冷、无汗、舌淡"呢？那可能是有寒外束、内有郁热。
          </p>
          <p>
            <strong>对策</strong>：不要急着下结论，多看几组症状，尤其是舌象、脉象，这些客观指征往往能帮你排除错误选项。
          </p>

          <h3>误区二：忽略舌脉</h3>
          <p>
            舌象和脉象是辨证的重要依据，很多初学者只盯着症状，忽略舌脉。但如果症状和舌脉矛盾，往往舌脉更可靠——因为症状是病人主观感受，可能描述不准确，而舌脉是客观指征。
          </p>
          <p>
            <strong>对策</strong>：习惯性地把舌象和脉象作为辨证的必要条件。没有舌脉信息，辨证结论的可靠性就要打折扣。
          </p>

          <h3>误区三：虚实不分</h3>
          <p>
            这是新手最常犯的错误。看到病人"没力气"就以为是气虚，看到"口干"就以为是阴虚。但没力气也可能是湿困（实证），口干也可能是有瘀血（实证）——因为瘀血阻滞，津液上不去，也会口干，但这种口干不想喝水。
          </p>
          <p>
            <strong>对策</strong>：学会区分"真虚"和"假虚"。判断虚实的关键看舌象——虚证舌淡嫩、苔少；实证舌紫暗、苔厚腻。另外，虚证一般病程长、起病缓；实证一般病程短、起病急。
          </p>

          <h3>误区四：寒热混淆</h3>
          <p>
            寒证和热证看似容易区分，但临床上往往出现"假寒真热"或"假热真寒"。比如病人四肢冰冷、怕冷，看起来是寒证，但摸胸部是热的、舌红苔黄——这是热盛于里、阳气被郁不能外达的"真热假寒"。
          </p>
          <p>
            <strong>对策</strong>：判断寒热不能只看局部，要看全身。重点关注：口渴与否（喜冷饮还是热饮）、舌苔（黄为热、白为寒）、脉象（数为热、迟为寒）、二便（便秘尿黄多为热、便溏尿清多为寒）。
          </p>

          <h3>误区五：重局部轻整体</h3>
          <p>
            病人说头痛，你就只盯着头；说胃痛，你就只盯着胃。但头痛可能是肝阳上亢，也可能是气虚不升，还可能是风寒外束。胃痛可能是肝气犯胃，也可能是脾胃虚寒，还可能是食积。
          </p>
          <p>
            <strong>对策</strong>：始终用"房间、宝贝、毛病、坏蛋"框架来分析，不要被病人的主诉牵着鼻子走。主诉只是一个线索，不是结论。
          </p>

          <h3>误区六：理论脱离实际</h3>
          <p>
            背了一堆证候名称和方剂，但到了临床上完全不知道怎么用。病人不会按照教科书生病，真实病人的症状往往是多种证候的混合，而且很多症状不典型。
          </p>
          <p>
            <strong>对策</strong>：从学的那一刻就开始练。书本上学到一个概念，马上问自己：这个在临床上会怎么表现？如果遇到一个病人有哪些症状，我该怎么判断？用"病例思维"代替"知识思维"。
          </p>

          <h3>误区七：追求"标准答案"</h3>
          <p>
            中医辨证没有标准答案，只有更合理的答案。同一个病人，不同的医生可能得出不同的辨证结论，只要都能治好病，就都是对的。不要追求"唯一正确的答案"，而要追求"最合理的解释"。
          </p>
          <p>
            <strong>对策</strong>：接受辨证的不确定性，学会"可能性分析"——列出几种可能的证候，然后逐一排除，留下的就是最可能的。当治疗效果不理想时，重新辨证，不要死守一个结论。
          </p>

          <h3>终极提醒</h3>
          <blockquote>
            <p><strong>辨证不是知识，是能力；不是背出来的，是练出来的。</strong></p>
          </blockquote>
          <p>
            附录的所有表格和口诀都是你的工具，但真正的辨证能力，来自于不断地观察、思考、实践和反思。祝你在中医辨证的道路上越走越远，越走越自信。
          </p>
        </section>

      </div>
    </div>
  )
}