import SectionImage from '../components/SectionImage'

export default function Module6() {
  return (
    <div className="page-enter-active">
      <div className="text-center mb-12">
        <span className="text-5xl">🔍</span>
        <h1 className="font-serif text-3xl sm:text-4xl font-bold text-ink-700 mt-4 mb-2">
          模块六：辨证实战——自己动手破案
        </h1>
        <div className="decorative-line mx-auto" />
        <p className="text-ink-500 text-lg">
          学完前五个模块，是时候亲自上阵了！——像侦探一样，用四步法破解疾病的密码
        </p>
      </div>

      <SectionImage
        prompt="Traditional Chinese medicine doctor examining patient in a warm clinical room, taking pulse, observing tongue, gentle professional atmosphere, soft natural window light, warm beige and brown tones, scholarly medical setting"
        alt="辨证实战"
      />

      <div className="content-section">
        {/* ========== sec-m6-1: 破案五步法 ========== */}
        <section id="sec-m6-1">
          <h2>一、破案五步法</h2>
          <p>
            辨证就像侦探破案。病人来找你，身上带着一堆"线索"（症状），你的任务就是根据这些线索，找出"凶手"（病因）、判断"作案地点"（病位）和"作案手法"（病性）。这套破案方法，我们总结为<strong>五个步骤</strong>，一步步来，就能揭开疾病的真相。
          </p>

          <h3>第一步：收集线索（问诊）</h3>
          <p>
            问诊是辨证的第一步，也是最关键的一步。一个好的侦探，首先要学会问问题。中医问诊有一套标准的顺序，叫<strong>"十问歌"</strong>，我们把它简化为七个方面，按照顺序逐一询问：
          </p>

          <h4>1. 寒热</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={3}>怕冷还是怕热？</td>
                <td>怕冷（恶寒），加衣盖被不缓解</td>
                <td>表寒证（风寒外束）</td>
              </tr>
              <tr>
                <td>怕冷，加衣盖被能缓解</td>
                <td>里寒证（阳虚）</td>
              </tr>
              <tr>
                <td>怕热，想脱衣服、吹风</td>
                <td>热证（实热或虚热）</td>
              </tr>
              <tr>
                <td rowSpan={2}>有没有发烧？</td>
                <td>发烧伴怕冷</td>
                <td>表证（病在卫分）</td>
              </tr>
              <tr>
                <td>高烧不怕冷，反而怕热</td>
                <td>里热证（病在气分）</td>
              </tr>
              <tr>
                <td rowSpan={2}>寒热交替出现？</td>
                <td>一阵冷一阵热（寒热往来）</td>
                <td>半表半里（少阳病）</td>
              </tr>
              <tr>
                <td>定时发热，下午或晚上加重</td>
                <td>阴虚发热或湿热</td>
              </tr>
            </tbody>
          </table>

          <h4>2. 出汗</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={4}>有没有出汗？</td>
                <td>不出汗，身上干爽</td>
                <td>表寒证（风寒束表，毛孔紧闭）</td>
              </tr>
              <tr>
                <td>有汗，出汗后怕风</td>
                <td>表虚证（卫气不固）</td>
              </tr>
              <tr>
                <td>白天稍动就出汗（自汗）</td>
                <td>气虚（卫气不固）</td>
              </tr>
              <tr>
                <td>晚上睡觉出汗（盗汗）</td>
                <td>阴虚（阴虚火旺，迫津外泄）</td>
              </tr>
              <tr>
                <td rowSpan={2}>出汗部位？</td>
                <td>头部出汗多</td>
                <td>上焦有热或湿热</td>
              </tr>
              <tr>
                <td>手脚心出汗</td>
                <td>阴虚或脾胃湿热</td>
              </tr>
            </tbody>
          </table>

          <h4>3. 疼痛</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={4}>哪里痛？</td>
                <td>头痛</td>
                <td>外感或肝阳上亢</td>
              </tr>
              <tr>
                <td>胸胁痛</td>
                <td>气滞（肝）或心肺问题</td>
              </tr>
              <tr>
                <td>胃脘痛</td>
                <td>胃的问题（寒、热、食积）</td>
              </tr>
              <tr>
                <td>腰痛</td>
                <td>肾虚或寒湿</td>
              </tr>
              <tr>
                <td rowSpan={4}>什么性质？</td>
                <td>胀痛、窜痛</td>
                <td>气滞</td>
              </tr>
              <tr>
                <td>刺痛、固定不移</td>
                <td>血瘀</td>
              </tr>
              <tr>
                <td>冷痛，得热减轻</td>
                <td>寒证</td>
              </tr>
              <tr>
                <td>灼痛，喜冷</td>
                <td>热证</td>
              </tr>
              <tr>
                <td rowSpan={2}>按压后感觉？</td>
                <td>按着舒服（喜按）</td>
                <td>虚证</td>
              </tr>
              <tr>
                <td>按着更痛（拒按）</td>
                <td>实证</td>
              </tr>
            </tbody>
          </table>

          <h4>4. 二便</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={4}>大便怎么样？</td>
                <td>便秘（干结难解）</td>
                <td>热证（津亏）、气滞或气虚</td>
              </tr>
              <tr>
                <td>腹泻（大便稀溏）</td>
                <td>寒证（脾虚）或湿热</td>
              </tr>
              <tr>
                <td>大便黏腻不爽，冲不干净</td>
                <td>湿气重（湿热或寒湿）</td>
              </tr>
              <tr>
                <td>大便先干后稀</td>
                <td>脾虚（脾气不足）</td>
              </tr>
              <tr>
                <td rowSpan={3}>小便怎么样？</td>
                <td>小便清长、量多</td>
                <td>寒证（阳虚）</td>
              </tr>
              <tr>
                <td>小便短黄、量少</td>
                <td>热证（津伤）</td>
              </tr>
              <tr>
                <td>尿频、夜尿多</td>
                <td>肾气虚（肾不固摄）</td>
              </tr>
            </tbody>
          </table>

          <h4>5. 饮食</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={2}>胃口怎么样？</td>
                <td>胃口差，不想吃</td>
                <td>脾虚或湿困</td>
              </tr>
              <tr>
                <td>胃口好，容易饿</td>
                <td>胃火（胃热炽盛）</td>
              </tr>
              <tr>
                <td rowSpan={2}>口渴吗？</td>
                <td>口渴想喝冷水</td>
                <td>热证（实热）</td>
              </tr>
              <tr>
                <td>口渴想喝热水，或不渴</td>
                <td>寒证或湿证</td>
              </tr>
              <tr>
                <td rowSpan={2}>嘴里什么味道？</td>
                <td>口苦</td>
                <td>肝胆有热（火）</td>
              </tr>
              <tr>
                <td>口淡无味</td>
                <td>脾虚（脾失健运）</td>
              </tr>
            </tbody>
          </table>

          <h4>6. 睡眠</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={3}>睡眠怎么样？</td>
                <td>难以入睡，翻来覆去</td>
                <td>心火旺或肝火（热扰心神）</td>
              </tr>
              <tr>
                <td>睡着了容易醒，多梦</td>
                <td>心血虚或心脾两虚</td>
              </tr>
              <tr>
                <td>嗜睡，怎么睡都不够</td>
                <td>湿气重或气虚</td>
              </tr>
              <tr>
                <td rowSpan={2}>梦多吗？</td>
                <td>做噩梦、惊恐的梦</td>
                <td>心胆气虚</td>
              </tr>
              <tr>
                <td>梦见找东西、赶路、着急</td>
                <td>思虑过度、心脾两虚</td>
              </tr>
            </tbody>
          </table>

          <h4>7. 月经（女性）</h4>
          <table>
            <thead>
              <tr>
                <th>问诊内容</th>
                <th>可能的答案</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={3}>经期怎么样？</td>
                <td>提前（周期短于21天）</td>
                <td>血热或气虚（不固摄）</td>
              </tr>
              <tr>
                <td>推后（周期长于35天）</td>
                <td>血寒、血虚或气滞</td>
              </tr>
              <tr>
                <td>先后不定期</td>
                <td>肝郁（气机紊乱）或肾虚</td>
              </tr>
              <tr>
                <td rowSpan={3}>经量和颜色？</td>
                <td>量多、色淡质稀</td>
                <td>气虚（不统血）</td>
              </tr>
              <tr>
                <td>量少、色淡质稀</td>
                <td>血虚</td>
              </tr>
              <tr>
                <td>量多、色深红、质稠</td>
                <td>血热</td>
              </tr>
              <tr>
                <td rowSpan={2}>有没有痛经？</td>
                <td>小腹冷痛，得热减轻</td>
                <td>寒凝血瘀</td>
              </tr>
              <tr>
                <td>小腹胀痛，经前加重</td>
                <td>气滞血瘀</td>
              </tr>
            </tbody>
          </table>

          <h3>第二步：望诊和切诊</h3>
          <p>
            问诊收集了病人的"口供"，接下来要用眼睛和手来验证。望诊和切诊是中医最具特色的诊断方法，也是最考验功力的地方。
          </p>

          <h4>望面色</h4>
          <table>
            <thead>
              <tr>
                <th>面色</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>面色苍白</td>
                <td>虚寒证（气血不足或阳虚）</td>
              </tr>
              <tr>
                <td>面色红赤</td>
                <td>热证（实热——满面通红；虚热——颧骨潮红）</td>
              </tr>
              <tr>
                <td>面色萎黄（黄而无光泽）</td>
                <td>脾虚（气血生化不足）</td>
              </tr>
              <tr>
                <td>面色晦暗、青紫</td>
                <td>瘀血或寒证</td>
              </tr>
              <tr>
                <td>面色发青</td>
                <td>寒证、痛证、惊风</td>
              </tr>
              <tr>
                <td>面色发黑（晦暗黧黑）</td>
                <td>肾虚（肾精亏虚）或瘀血</td>
              </tr>
            </tbody>
          </table>

          <h4>望舌头</h4>
          <p>
            舌诊是中医辨证最直观的手段。舌头就像身体的"显示屏"，脏腑的状况都会在上面反映出来。看舌头主要看两个方面：<strong>舌质</strong>（舌头的颜色和形态）和<strong>舌苔</strong>（舌面上的苔状物）。
          </p>
          <table>
            <thead>
              <tr>
                <th>观察项目</th>
                <th>具体表现</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td rowSpan={4}><strong>舌质颜色</strong></td>
                <td>淡白舌</td>
                <td>虚寒（气血不足或阳虚）</td>
              </tr>
              <tr>
                <td>红舌</td>
                <td>热证（实热或虚热）</td>
              </tr>
              <tr>
                <td>绛舌（深红）</td>
                <td>热入营血（病情危重）</td>
              </tr>
              <tr>
                <td>紫暗舌</td>
                <td>瘀血</td>
              </tr>
              <tr>
                <td rowSpan={3}><strong>舌苔颜色</strong></td>
                <td>白苔</td>
                <td>表证、寒证</td>
              </tr>
              <tr>
                <td>黄苔</td>
                <td>热证（黄越深，热越重）</td>
              </tr>
              <tr>
                <td>灰黑苔</td>
                <td>里热极重或里寒极重</td>
              </tr>
              <tr>
                <td rowSpan={4}><strong>舌苔质地</strong></td>
                <td>薄苔</td>
                <td>病轻（病在表）</td>
              </tr>
              <tr>
                <td>厚苔</td>
                <td>病重（病在里，或有食积、湿浊）</td>
              </tr>
              <tr>
                <td>腻苔（苔致密、颗粒细腻）</td>
                <td>湿浊、痰饮、食积</td>
              </tr>
              <tr>
                <td>燥苔（苔干燥、津液不足）</td>
                <td>津伤（热盛伤津或阴虚）</td>
              </tr>
              <tr>
                <td rowSpan={2}><strong>舌体形态</strong></td>
                <td>胖大舌、边有齿痕</td>
                <td>脾虚（水湿内停）</td>
              </tr>
              <tr>
                <td>瘦小舌、舌有裂纹</td>
                <td>阴虚（津液亏虚）</td>
              </tr>
            </tbody>
          </table>

          <h4>切脉</h4>
          <p>
            脉诊是中医的"独门秘籍"，通过触摸手腕处的脉搏，感知气血的运行状态。常见脉象及意义：
          </p>
          <table>
            <thead>
              <tr>
                <th>脉象</th>
                <th>手感</th>
                <th>提示什么</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>浮脉</strong></td>
                <td>轻轻一摸就能感觉到，重按反而弱</td>
                <td>表证（病在体表，如感冒）</td>
              </tr>
              <tr>
                <td><strong>沉脉</strong></td>
                <td>轻摸不到，重按才能感觉到</td>
                <td>里证（病在脏腑深处）</td>
              </tr>
              <tr>
                <td><strong>数脉</strong></td>
                <td>跳得快（每分钟超过90次）</td>
                <td>热证（有热）</td>
              </tr>
              <tr>
                <td><strong>迟脉</strong></td>
                <td>跳得慢（每分钟少于60次）</td>
                <td>寒证（有寒）</td>
              </tr>
              <tr>
                <td><strong>滑脉</strong></td>
                <td>流利圆滑，像珠子在盘子里滚</td>
                <td>痰饮、食积、实热，或正常妊娠</td>
              </tr>
              <tr>
                <td><strong>涩脉</strong></td>
                <td>不流利，像刀刮竹子的感觉</td>
                <td>血瘀、气滞、精亏</td>
              </tr>
              <tr>
                <td><strong>弦脉</strong></td>
                <td>端直以长，像按在琴弦上</td>
                <td>肝胆病、气滞、痛证</td>
              </tr>
              <tr>
                <td><strong>细脉</strong></td>
                <td>细如丝线，但能摸到</td>
                <td>气血两虚、阴虚</td>
              </tr>
              <tr>
                <td><strong>弱脉</strong></td>
                <td>沉而细，按不到</td>
                <td>阳气虚衰</td>
              </tr>
              <tr>
                <td><strong>洪脉</strong></td>
                <td>来势汹涌，宽大有力</td>
                <td>热盛（热邪炽盛，气血沸腾）</td>
              </tr>
            </tbody>
          </table>

          <h3>第三步：定位房间（症状与房间对照表）</h3>
          <p>
            收集完线索后，第一步判断是：<strong>问题出在哪个"房间"？</strong>也就是确定病位。下面是根据症状判断病位的对照表：
          </p>
          <table>
            <thead>
              <tr>
                <th>症状</th>
                <th>病位（房间）</th>
                <th>判断依据</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>心悸、失眠、胸闷、舌尖红</td>
                <td><strong>心</strong></td>
                <td>心主血脉、主藏神，舌为心之苗</td>
              </tr>
              <tr>
                <td>胁痛、情绪抑郁、叹气、目赤</td>
                <td><strong>肝</strong></td>
                <td>肝主疏泄，开窍于目，肝经循行两胁</td>
              </tr>
              <tr>
                <td>食欲不振、腹胀、便溏、肌肉消瘦</td>
                <td><strong>脾</strong></td>
                <td>脾主运化、主四肢肌肉</td>
              </tr>
              <tr>
                <td>咳嗽、气喘、鼻塞、容易感冒</td>
                <td><strong>肺</strong></td>
                <td>肺主呼吸、主宣发肃降，开窍于鼻</td>
              </tr>
              <tr>
                <td>腰膝酸软、耳鸣、尿频、脱发</td>
                <td><strong>肾</strong></td>
                <td>肾主骨生髓，开窍于耳，腰为肾之府</td>
              </tr>
              <tr>
                <td>打嗝、反酸、恶心、胃痛</td>
                <td><strong>胃</strong></td>
                <td>胃主受纳、主通降</td>
              </tr>
              <tr>
                <td>咳嗽、怕冷、无汗、头痛</td>
                <td><strong>卫分（肺表）</strong></td>
                <td>卫气布于体表，肺主皮毛</td>
              </tr>
              <tr>
                <td>高烧、大渴、大汗、脉洪大</td>
                <td><strong>气分（肺胃）</strong></td>
                <td>气分热盛，肺胃为主要战场</td>
              </tr>
            </tbody>
          </table>

          <h3>第四步：判断毛病和宝贝（症状特征对照表）</h3>
          <p>
            确定病位之后，接下来要判断：<strong>这个"房间"出了什么毛病？</strong>是"不够用"（虚），还是"堵住了"（实）？是"方向反了"（逆），还是"温度不对"（寒热）？下面是对照表：
          </p>
          <table>
            <thead>
              <tr>
                <th>毛病类型</th>
                <th>核心症状</th>
                <th>舌象</th>
                <th>脉象</th>
                <th>涉及的"宝贝"</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>气虚</strong></td>
                <td>乏力、气短、自汗、动则加重</td>
                <td>淡胖、齿痕</td>
                <td>虚、弱</td>
                <td>气不足</td>
              </tr>
              <tr>
                <td><strong>血虚</strong></td>
                <td>面色苍白、头晕眼花、心悸失眠</td>
                <td>淡白、瘦薄</td>
                <td>细</td>
                <td>血不足</td>
              </tr>
              <tr>
                <td><strong>阴虚</strong></td>
                <td>五心烦热、潮热盗汗、口干咽燥</td>
                <td>红、少苔或无苔、裂纹</td>
                <td>细数</td>
                <td>津/液不足</td>
              </tr>
              <tr>
                <td><strong>阳虚</strong></td>
                <td>畏寒怕冷、四肢不温、喜热饮</td>
                <td>淡胖、苔白滑</td>
                <td>沉迟无力</td>
                <td>气不足（阳）</td>
              </tr>
              <tr>
                <td><strong>气滞</strong></td>
                <td>胀痛、窜痛、叹气、情绪相关</td>
                <td>可正常或略暗</td>
                <td>弦</td>
                <td>气不通</td>
              </tr>
              <tr>
                <td><strong>血瘀</strong></td>
                <td>刺痛固定、面色晦暗、唇紫</td>
                <td>紫暗、瘀斑瘀点</td>
                <td>涩</td>
                <td>血不通</td>
              </tr>
              <tr>
                <td><strong>水停/痰湿</strong></td>
                <td>身重、头重如裹、苔腻、浮肿</td>
                <td>胖大、齿痕、苔腻</td>
                <td>濡、滑</td>
                <td>津/液不通</td>
              </tr>
              <tr>
                <td><strong>食积</strong></td>
                <td>胃胀、打嗝酸腐、苔厚腻</td>
                <td>苔厚腻（黄或白）</td>
                <td>滑</td>
                <td>胃不通</td>
              </tr>
              <tr>
                <td><strong>寒证</strong></td>
                <td>怕冷、冷痛、得热减轻、分泌物清稀</td>
                <td>淡、苔白</td>
                <td>紧、迟</td>
                <td>温度太低</td>
              </tr>
              <tr>
                <td><strong>热证</strong></td>
                <td>发热、口渴喜冷、面红、分泌物黄稠</td>
                <td>红、苔黄</td>
                <td>数</td>
                <td>温度太高</td>
              </tr>
              <tr>
                <td><strong>气逆</strong></td>
                <td>咳嗽、呕吐、打嗝、反酸</td>
                <td>不定</td>
                <td>弦、滑</td>
                <td>方向反了</td>
              </tr>
            </tbody>
          </table>

          <h3>第五步：揪出坏蛋（诱因对照表）</h3>
          <p>
            最后一步，找出导致疾病的"坏蛋"——也就是病因。结合前面收集的线索，判断是哪一种致病因素在作祟：
          </p>
          <table>
            <thead>
              <tr>
                <th>诱因（坏蛋）</th>
                <th>典型线索</th>
                <th>常见搭配</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>风邪</strong></td>
                <td>起病急、变化快、怕风、游走性疼痛、鼻塞咽痒</td>
                <td>风寒、风热、风湿</td>
              </tr>
              <tr>
                <td><strong>寒邪</strong></td>
                <td>怕冷重、不出汗、冷痛、得热减轻、分泌物清稀</td>
                <td>风寒、寒湿、寒凝</td>
              </tr>
              <tr>
                <td><strong>暑邪</strong></td>
                <td>夏季发病、高热、大汗、口渴、乏力、胸闷恶心</td>
                <td>暑湿</td>
              </tr>
              <tr>
                <td><strong>湿邪</strong></td>
                <td>身体沉重、头重如裹、苔腻、大便黏腻、病程缠绵</td>
                <td>风寒湿、湿热、寒湿</td>
              </tr>
              <tr>
                <td><strong>燥邪</strong></td>
                <td>口鼻干燥、皮肤干裂、干咳少痰、秋季多发</td>
                <td>温燥、凉燥</td>
              </tr>
              <tr>
                <td><strong>火/热邪</strong></td>
                <td>高烧、面红、口渴喜冷、黄痰黄涕、便秘尿黄</td>
                <td>风热、湿热、热毒</td>
              </tr>
              <tr>
                <td><strong>情志（怒）</strong></td>
                <td>爱生气、胁痛、头痛、面红、脉弦</td>
                <td>肝气郁结、肝火上炎</td>
              </tr>
              <tr>
                <td><strong>情志（思虑）</strong></td>
                <td>思虑过度、食欲不振、失眠、健忘</td>
                <td>心脾两虚、气结</td>
              </tr>
              <tr>
                <td><strong>饮食不节</strong></td>
                <td>暴饮暴食、吃生冷油腻、胃胀、打嗝酸腐</td>
                <td>食积、湿热</td>
              </tr>
              <tr>
                <td><strong>劳倦过度</strong></td>
                <td>长期劳累、乏力、气短、腰酸</td>
                <td>气虚、肾虚</td>
              </tr>
            </tbody>
          </table>

          <h3>三个破案实例</h3>

          <h4>实例一：小王——风寒感冒</h4>
          <p>
            <strong>案情：</strong>小王，男，25岁。昨天淋了一场大雨，今天开始不舒服。
          </p>
          <p>
            <strong>问诊记录：</strong>
          </p>
          <ul>
            <li>寒热：非常怕冷，盖了厚被子还觉得冷，体温38.2℃</li>
            <li>出汗：不出汗，皮肤干爽</li>
            <li>疼痛：头痛、全身酸痛</li>
            <li>二便：小便清长，大便正常</li>
            <li>饮食：不想喝水，喝热水舒服</li>
            <li>睡眠：正常（但怕冷睡不安稳）</li>
          </ul>
          <p>
            <strong>望诊切诊：</strong>面色偏白，舌淡红苔薄白，脉浮紧。
          </p>

          <h4>破案过程</h4>
          <table>
            <thead>
              <tr>
                <th>步骤</th>
                <th>分析</th>
                <th>结论</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>第一步：收集线索</strong></td>
                <td>怕冷重、不出汗、头痛身痛、不渴喜热饮、小便清长、舌淡苔白、脉浮紧</td>
                <td>全部指向寒证、表证</td>
              </tr>
              <tr>
                <td><strong>第二步：定位房间</strong></td>
                <td>怕冷、发热、无汗、头痛——病在卫分（体表），关联肺（肺主皮毛）</td>
                <td>病位：<strong>卫分 + 肺</strong></td>
              </tr>
              <tr>
                <td><strong>第三步：判断毛病</strong></td>
                <td>怕冷重（寒）、无汗（寒主收引）、头身痛（寒凝经脉）、脉浮紧（寒束于表）</td>
                <td>毛病：<strong>寒</strong>（表寒实证）</td>
              </tr>
              <tr>
                <td><strong>第四步：揪出坏蛋</strong></td>
                <td>淋雨受凉后发病，怕冷重、无汗——典型的风寒外袭</td>
                <td>坏蛋：<strong>风寒</strong></td>
              </tr>
              <tr>
                <td><strong>第五步：生成辨证链</strong></td>
                <td>风寒 → 滞（卫气被郁）→ 无汗、发热、头身痛 → 肺 + 卫分</td>
                <td><strong>风寒 × 滞 × 气 × 肺 + 卫分</strong></td>
              </tr>
            </tbody>
          </table>
          <p>
            <strong>治法：</strong>辛温解表，宣肺散寒。代表方：麻黄汤或荆防败毒散。
          </p>

          <h4>实例二：李大姐——心脾两虚</h4>
          <p>
            <strong>案情：</strong>李大姐，45岁，最近半年身体状况越来越差。
          </p>
          <p>
            <strong>问诊记录：</strong>
          </p>
          <ul>
            <li>寒热：不太怕冷，但手脚偏凉</li>
            <li>出汗：白天稍动就出汗（自汗）</li>
            <li>疼痛：没有明显疼痛，但总觉得累</li>
            <li>二便：大便稀溏，小便正常</li>
            <li>饮食：胃口不好，吃得少，不觉得饿</li>
            <li>睡眠：失眠多梦，容易醒，醒了睡不着</li>
            <li>月经：量少、色淡，周期推迟</li>
          </ul>
          <p>
            <strong>望诊切诊：</strong>面色萎黄，精神疲惫，舌淡胖边有齿痕、苔薄白，脉细弱。
          </p>

          <h4>破案过程</h4>
          <table>
            <thead>
              <tr>
                <th>步骤</th>
                <th>分析</th>
                <th>结论</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>第一步：收集线索</strong></td>
                <td>乏力、自汗、食欲不振、便溏（脾虚）；失眠多梦、月经量少色淡（血虚）；舌淡胖齿痕、脉细弱</td>
                <td>气虚+血虚，病位在心、脾</td>
              </tr>
              <tr>
                <td><strong>第二步：定位房间</strong></td>
                <td>失眠多梦、心悸不安——心（主藏神）；食欲不振、便溏、乏力——脾（主运化）</td>
                <td>病位：<strong>心 + 脾</strong></td>
              </tr>
              <tr>
                <td><strong>第三步：判断毛病</strong></td>
                <td>乏力、自汗（气虚）；面色萎黄、月经量少（血虚）；舌淡脉细（气血两虚）</td>
                <td>毛病：<strong>虚（气虚 + 血虚）</strong></td>
              </tr>
              <tr>
                <td><strong>第四步：揪出坏蛋</strong></td>
                <td>患者长期思虑过度（照顾家庭、工作压力大），劳倦伤脾，暗耗心血</td>
                <td>坏蛋：<strong>思虑 + 劳倦</strong></td>
              </tr>
              <tr>
                <td><strong>第五步：生成辨证链</strong></td>
                <td>思虑 + 劳倦 → 虚（血虚 + 气虚）→ 失眠、纳差、乏力、月经少 → 心 + 脾</td>
                <td><strong>思虑 + 劳倦 × 虚 × 血 + 气 × 心 + 脾</strong></td>
              </tr>
            </tbody>
          </table>
          <p>
            <strong>治法：</strong>补益心脾，养血安神。代表方：归脾汤。
          </p>

          <h4>实例三：老赵——肝气犯胃</h4>
          <p>
            <strong>案情：</strong>老赵，52岁，最近三个月总感觉胃不舒服。
          </p>
          <p>
            <strong>问诊记录：</strong>
          </p>
          <ul>
            <li>寒热：不发热，不怕冷</li>
            <li>出汗：正常</li>
            <li>疼痛：胃胀痛，有时胁肋也胀痛，痛的位置不固定，窜来窜去</li>
            <li>二便：大便时干时稀，排便不畅</li>
            <li>饮食：胃口还行，但吃完就胀，打嗝多，反酸</li>
            <li>睡眠：入睡困难，心烦易怒</li>
          </ul>
          <p>
            <strong>望诊切诊：</strong>面色略暗，舌质偏红苔薄黄，脉弦。问其最近是否常生气，老赵叹气说："跟孩子生了好几个月的气了！"
          </p>

          <h4>破案过程</h4>
          <table>
            <thead>
              <tr>
                <th>步骤</th>
                <th>分析</th>
                <th>结论</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>第一步：收集线索</strong></td>
                <td>胃胀痛、胁肋胀痛、窜痛（气滞）；打嗝反酸（气逆）；心烦易怒（肝火）；脉弦（气滞）</td>
                <td>气滞+气逆，病位在肝、胃</td>
              </tr>
              <tr>
                <td><strong>第二步：定位房间</strong></td>
                <td>胁肋胀痛、心烦易怒、脉弦——肝（主疏泄）；胃胀、打嗝反酸——胃（主通降）</td>
                <td>病位：<strong>肝 + 胃</strong></td>
              </tr>
              <tr>
                <td><strong>第三步：判断毛病</strong></td>
                <td>胀痛窜痛（气滞）；打嗝反酸（气逆）；舌红苔黄（有热象，肝郁化火）</td>
                <td>毛病：<strong>滞 + 逆</strong>（气滞为主，兼气逆）</td>
              </tr>
              <tr>
                <td><strong>第四步：揪出坏蛋</strong></td>
                <td>患者因与孩子生气，怒则气上，肝气郁结，横逆犯胃</td>
                <td>坏蛋：<strong>怒（情志）</strong></td>
              </tr>
              <tr>
                <td><strong>第五步：生成辨证链</strong></td>
                <td>怒 → 滞（肝气郁结）+ 逆（肝气上逆、胃气上逆）→ 胁痛、胃胀、反酸 → 肝 + 胃</td>
                <td><strong>怒 × 滞 + 逆 × 气 × 肝 + 胃</strong></td>
              </tr>
            </tbody>
          </table>
          <p>
            <strong>治法：</strong>疏肝理气，和胃降逆。代表方：柴胡疏肝散合左金丸。
          </p>

          <h3>练习题答案</h3>
          <p>
            以下为本模块练习题的答案，供自测使用。建议先独立完成练习，再对照答案。
          </p>

          <h4>初级题——填四要素</h4>
          <table>
            <thead>
              <tr>
                <th>题号</th>
                <th>辨证结论</th>
                <th>答案</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>小红头晕乏力、面色苍白、月经量少色淡、舌淡脉细</td>
                <td>病位：心、肝；毛病：血虚；宝贝：血；坏蛋：劳倦/思虑</td>
              </tr>
              <tr>
                <td>2</td>
                <td>小张咳嗽黄痰、咽喉肿痛、发热口渴、舌红苔黄、脉数</td>
                <td>病位：肺；毛病：热；宝贝：津/气；坏蛋：热邪/风热</td>
              </tr>
              <tr>
                <td>3</td>
                <td>刘大爷腰膝酸软、夜尿频多、怕冷畏寒、舌淡苔白、脉沉迟</td>
                <td>病位：肾；毛病：虚（阳虚）；宝贝：气（阳）；坏蛋：年老/劳倦</td>
              </tr>
            </tbody>
          </table>

          <h4>中级题——写生成链</h4>
          <table>
            <thead>
              <tr>
                <th>题号</th>
                <th>辨证结论</th>
                <th>答案</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>风寒袭肺证</td>
                <td>风寒 → 滞（肺气不宣）→ 咳嗽、鼻塞、无汗 → 肺 + 卫分</td>
              </tr>
              <tr>
                <td>2</td>
                <td>肝郁气滞证</td>
                <td>怒/思虑 → 滞（肝气郁结）→ 胁肋胀痛、叹气、情绪抑郁 → 肝</td>
              </tr>
              <tr>
                <td>3</td>
                <td>脾胃湿热证</td>
                <td>饮食不节/湿邪 → 滞 + 热（湿热蕴结脾胃）→ 脘腹胀满、大便黏腻、苔黄腻 → 脾 + 胃</td>
              </tr>
            </tbody>
          </table>

          <h4>高级题——完整破案</h4>
          <p><strong>案例一：陈奶奶，68岁，反复咳嗽气喘5年，加重1周。</strong></p>
          <p>症见：咳嗽气喘，痰白清稀泡沫状，怕冷，背部尤其怕冷，四肢不温，小便清长，夜间咳嗽加重不能平卧。舌淡胖苔白滑，脉沉弦。</p>
          <p><strong>答案：</strong></p>
          <ul>
            <li><strong>病位：</strong>肺 + 肾</li>
            <li><strong>毛病：</strong>虚（阳虚）+ 水停（饮邪内停）</li>
            <li><strong>宝贝：</strong>气（阳）+ 津（水液代谢失常）</li>
            <li><strong>坏蛋：</strong>年老正虚 + 寒邪</li>
            <li><strong>生成链：</strong>年老 + 寒 → 虚（阳虚）+ 停（寒饮伏肺）→ 咳喘、痰白清稀、怕冷、不能平卧 → 肺 + 肾</li>
            <li><strong>辨证结论：</strong>阳虚寒饮伏肺（支饮）</li>
          </ul>

          <p><strong>案例二：王先生，35岁，胃痛反复发作3年，最近应酬后加重。</strong></p>
          <p>症见：胃脘灼痛，反酸烧心，口苦口干，喜冷饮，大便干结，小便短黄，心烦易怒。舌红苔黄，脉弦数。</p>
          <p><strong>答案：</strong></p>
          <ul>
            <li><strong>病位：</strong>肝 + 胃</li>
            <li><strong>毛病：</strong>热 + 逆（肝火犯胃，胃气上逆）</li>
            <li><strong>宝贝：</strong>气（肝气、胃气）+ 津（被热耗伤）</li>
            <li><strong>坏蛋：</strong>饮食不节（应酬喝酒）+ 情志不畅（怒）</li>
            <li><strong>生成链：</strong>饮食不节 + 怒 → 热 + 逆（肝火犯胃）→ 胃脘灼痛、反酸烧心、口苦便秘 → 肝 + 胃</li>
            <li><strong>辨证结论：</strong>肝火犯胃证</li>
          </ul>

          <p><strong>案例三：小丽，28岁，月经不调半年。</strong></p>
          <p>症见：月经周期推迟（35-40天一行），量少色暗有血块，经前小腹胀痛，乳房胀痛，心情烦躁，叹气，舌暗红苔薄白，脉弦涩。</p>
          <p><strong>答案：</strong></p>
          <ul>
            <li><strong>病位：</strong>肝 + 胞宫（冲任）</li>
            <li><strong>毛病：</strong>滞（气滞）+ 瘀（血瘀）</li>
            <li><strong>宝贝：</strong>气（肝气郁滞）+ 血（瘀血阻滞）</li>
            <li><strong>坏蛋：</strong>情志不畅（怒/忧）</li>
            <li><strong>生成链：</strong>情志不畅 → 滞（肝气郁结）+ 瘀（血行不畅）→ 月经推迟、量少血块、经前胀痛 → 肝 + 胞宫</li>
            <li><strong>辨证结论：</strong>肝郁气滞血瘀证</li>
          </ul>
        </section>

        {/* ========== sec-m6-2: 常见病辨证指南 ========== */}
        <section id="sec-m6-2">
          <h2>二、常见病辨证指南</h2>
          <p>
            掌握了五步破案法之后，我们来看几个最常见疾病的辨证。每个病下面列出最常见的几种证型，记住这些典型表现，遇到类似情况就能快速判断。
          </p>

          <h3>感冒</h3>
          <p>
            感冒是最常见的疾病，中医根据病因和表现分为四种主要证型。感冒的辨证要点是看<strong>寒热轻重、汗的有无、痰涕的颜色和质地</strong>。
          </p>

          <h4>风寒感冒</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>怕冷重、发热轻、无汗、头身痛</td>
              </tr>
              <tr>
                <td><strong>鼻咽症状</strong></td>
                <td>鼻塞流清涕（像清水一样）、咽喉痒</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰白稀薄</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌淡红苔薄白</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉浮紧</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>辛温解表（麻黄汤、荆防败毒散）</td>
              </tr>
            </tbody>
          </table>

          <h4>风热感冒</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>发热重、怕冷轻、有汗（或少汗）、头痛</td>
              </tr>
              <tr>
                <td><strong>鼻咽症状</strong></td>
                <td>鼻塞流黄稠涕、咽喉肿痛、口干</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰黄黏稠</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌尖红苔薄黄</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉浮数</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>辛凉解表（银翘散、桑菊饮）</td>
              </tr>
            </tbody>
          </table>

          <h4>暑湿感冒</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>夏季发病，头重身沉、胸闷恶心</td>
              </tr>
              <tr>
                <td><strong>鼻咽症状</strong></td>
                <td>鼻塞流涕、咽部不爽</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰白黏或少痰</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌苔白腻或黄腻</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉濡或滑</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>解表化湿（藿香正气散）</td>
              </tr>
            </tbody>
          </table>

          <h4>气虚感冒</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>反复感冒、病程长、感冒后不易好</td>
              </tr>
              <tr>
                <td><strong>鼻咽症状</strong></td>
                <td>鼻塞流涕、但症状较轻</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>气短乏力、自汗、面色苍白</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌淡苔薄白</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉浮无力</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>益气解表（参苏饮、玉屏风散）</td>
              </tr>
            </tbody>
          </table>

          <h4>感冒证型鉴别表</h4>
          <div className="overflow-x-auto">
            <table>
              <thead>
                <tr>
                  <th>鉴别要点</th>
                  <th>风寒感冒</th>
                  <th>风热感冒</th>
                  <th>暑湿感冒</th>
                  <th>气虚感冒</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>怕冷/发热</strong></td>
                  <td>怕冷重、发热轻</td>
                  <td>发热重、怕冷轻</td>
                  <td>发热、怕冷均不著</td>
                  <td>怕冷、发热均轻</td>
                </tr>
                <tr>
                  <td><strong>汗</strong></td>
                  <td>无汗</td>
                  <td>有汗或少汗</td>
                  <td>有汗</td>
                  <td>自汗</td>
                </tr>
                <tr>
                  <td><strong>鼻涕</strong></td>
                  <td>清涕</td>
                  <td>黄稠涕</td>
                  <td>白黏涕</td>
                  <td>清涕</td>
                </tr>
                <tr>
                  <td><strong>痰</strong></td>
                  <td>白稀痰</td>
                  <td>黄黏痰</td>
                  <td>白黏痰</td>
                  <td>少痰</td>
                </tr>
                <tr>
                  <td><strong>舌苔</strong></td>
                  <td>薄白</td>
                  <td>薄黄</td>
                  <td>白腻/黄腻</td>
                  <td>薄白</td>
                </tr>
                <tr>
                  <td><strong>脉象</strong></td>
                  <td>浮紧</td>
                  <td>浮数</td>
                  <td>濡/滑</td>
                  <td>浮无力</td>
                </tr>
                <tr>
                  <td><strong>季节</strong></td>
                  <td>秋冬多发</td>
                  <td>春夏多发</td>
                  <td>夏季（长夏）</td>
                  <td>四季均可</td>
                </tr>
                <tr>
                  <td><strong>体质</strong></td>
                  <td>正常人</td>
                  <td>偏热体质</td>
                  <td>湿气重者</td>
                  <td>气虚体质</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3>咳嗽</h3>
          <p>
            咳嗽是肺系疾病最常见的症状。"咳"是有声无痰，"嗽"是有痰无声，临床上一般统称咳嗽。辨证要点是看<strong>痰的颜色、质地、量，以及伴随的寒热表现</strong>。
          </p>

          <h4>风寒咳嗽</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>咳嗽声重、气急咽痒</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰白稀薄、容易咳出</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>怕冷、发热、无汗、头痛、鼻塞流清涕</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌淡红苔薄白</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉浮或浮紧</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>疏风散寒、宣肺止咳（三拗汤合止嗽散）</td>
              </tr>
            </tbody>
          </table>

          <h4>风热咳嗽</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>咳嗽剧烈、喉咙干痛</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰黄黏稠、不易咳出</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>发热、怕风、有汗、口渴、鼻流黄涕</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌尖红苔薄黄</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉浮数</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>疏风清热、宣肺止咳（桑菊饮）</td>
              </tr>
            </tbody>
          </table>

          <h4>痰湿咳嗽</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>咳嗽反复发作、痰多易咳</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰白黏腻或稠厚成块，晨起或饭后加重</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>胸口闷胀、胃部胀满、食欲不振、身体困重</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌苔白腻</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉濡或滑</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>燥湿化痰、理气止咳（二陈汤合三子养亲汤）</td>
              </tr>
            </tbody>
          </table>

          <h4>阴虚咳嗽</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>干咳无痰或少痰、声音嘶哑</td>
              </tr>
              <tr>
                <td><strong>痰</strong></td>
                <td>痰少黏稠不易咳出，或痰中带血丝</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>口干咽燥、午后潮热、手足心热、夜间盗汗</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌红少苔或无苔</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉细数</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>养阴润肺、化痰止咳（沙参麦冬汤）</td>
              </tr>
            </tbody>
          </table>

          <h3>胃痛</h3>
          <p>
            胃痛（胃脘痛）是消化系统最常见的症状。辨证要点是看<strong>疼痛的性质（冷痛、灼痛、胀痛）、与饮食的关系、按压后的反应</strong>。
          </p>

          <h4>寒邪犯胃</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>胃痛暴作（突然发作）、冷痛剧烈</td>
              </tr>
              <tr>
                <td><strong>疼痛特点</strong></td>
                <td>得热痛减、遇寒加重、喜按喜温</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>口不渴、喜热饮、怕冷、手足不温</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌淡苔白</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉弦紧</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>温胃散寒、行气止痛（良附丸）</td>
              </tr>
            </tbody>
          </table>

          <h4>食积胃痛</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>胃胀痛、拒按、疼痛与饮食有关</td>
              </tr>
              <tr>
                <td><strong>疼痛特点</strong></td>
                <td>胀满疼痛、按之加重、嗳气酸腐、吐后痛减</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>打嗝有酸腐味、恶心呕吐、大便不爽或腹泻酸臭</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌苔厚腻（黄或白）</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉滑</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>消食导滞（保和丸）</td>
              </tr>
            </tbody>
          </table>

          <h4>肝气犯胃</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>胃胀痛连及两胁、情绪波动时加重</td>
              </tr>
              <tr>
                <td><strong>疼痛特点</strong></td>
                <td>胀痛、窜痛、嗳气后减轻</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>爱叹气、烦躁易怒、反酸烧心、胸闷</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌红苔薄黄</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉弦</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>疏肝理气、和胃止痛（柴胡疏肝散）</td>
              </tr>
            </tbody>
          </table>

          <h4>胃热炽盛</h4>
          <table>
            <thead>
              <tr>
                <th>维度</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>核心症状</strong></td>
                <td>胃脘灼痛、烧心反酸</td>
              </tr>
              <tr>
                <td><strong>疼痛特点</strong></td>
                <td>灼痛、得冷减轻、得热加重、拒按</td>
              </tr>
              <tr>
                <td><strong>伴随症状</strong></td>
                <td>口渴喜冷饮、口臭、牙龈肿痛、便秘、小便短黄</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌红苔黄厚或黄燥</td>
              </tr>
              <tr>
                <td><strong>脉象</strong></td>
                <td>脉滑数</td>
              </tr>
              <tr>
                <td><strong>治法</strong></td>
                <td>清胃泻热（清胃散）</td>
              </tr>
            </tbody>
          </table>
        </section>

        {/* ========== sec-m6-3: 练习题库 ========== */}
        <section id="sec-m6-3">
          <h2>三、练习题库</h2>
          <p>
            以下练习题分为三个难度级别，循序渐進，帮助你将所学的辨证知识转化为实战能力。建议先独立完成，再对照前面的答案检查。
          </p>

          <h3>初级题——填四要素</h3>
          <p>
            请根据病例描述，填写"病位、毛病、宝贝、坏蛋"四要素。
          </p>

          <h4>第1题</h4>
          <p>
            小红，32岁，最近半年经常头晕眼花，蹲下站起来时眼前发黑。面色苍白没有光泽，嘴唇颜色淡，指甲苍白易断。月经量越来越少，颜色淡红。经常心悸、失眠多梦。舌淡苔薄白，脉细。
          </p>
          <ul>
            <li>病位：______</li>
            <li>毛病：______</li>
            <li>宝贝：______</li>
            <li>坏蛋：______</li>
          </ul>

          <h4>第2题</h4>
          <p>
            小张，22岁，昨天开始发烧（38.5℃），怕冷较轻，有汗，喉咙痛得厉害，鼻子里呼出的气都是热的。咳嗽有黄稠痰，口渴想喝冷水。舌红苔薄黄，脉浮数。
          </p>
          <ul>
            <li>病位：______</li>
            <li>毛病：______</li>
            <li>宝贝：______</li>
            <li>坏蛋：______</li>
          </ul>

          <h4>第3题</h4>
          <p>
            刘大爷，70岁，近两年来总觉得腰膝酸软无力，走路时间长了腰就直不起来。特别怕冷，冬天比别人多穿两件衣服。晚上要起夜三四次，小便清长。大便稀溏，吃凉的就要拉肚子。舌淡胖苔白滑，脉沉迟无力。
          </p>
          <ul>
            <li>病位：______</li>
            <li>毛病：______</li>
            <li>宝贝：______</li>
            <li>坏蛋：______</li>
          </ul>

          <h3>中级题——写生成链</h3>
          <p>请根据辨证结论，写出完整的"病因→病机→症状→病位"生成链。</p>

          <h4>第1题：风寒袭肺证</h4>
          <p>生成链：______</p>

          <h4>第2题：肝郁气滞证</h4>
          <p>生成链：______</p>

          <h4>第3题：脾胃湿热证</h4>
          <p>生成链：______</p>

          <h3>高级题——完整破案</h3>
          <p>以下为完整的临床病例，请运用五步破案法，完成完整的辨证分析。</p>

          <h4>案例一</h4>
          <p>陈奶奶，68岁，反复咳嗽气喘5年，加重1周。症见：咳嗽气喘，痰白清稀泡沫状，怕冷，背部尤其怕冷，四肢不温，小便清长，夜间咳嗽加重不能平卧。舌淡胖苔白滑，脉沉弦。</p>
          <p>请写出：病位、毛病、宝贝、坏蛋、生成链、辨证结论。</p>

          <h4>案例二</h4>
          <p>王先生，35岁，胃痛反复发作3年，最近应酬后加重。症见：胃脘灼痛，反酸烧心，口苦口干，喜冷饮，大便干结，小便短黄，心烦易怒。舌红苔黄，脉弦数。</p>
          <p>请写出：病位、毛病、宝贝、坏蛋、生成链、辨证结论。</p>

          <h4>案例三</h4>
          <p>小丽，28岁，月经不调半年。症见：月经周期推迟（35-40天一行），量少色暗有血块，经前小腹胀痛，乳房胀痛，心情烦躁，叹气，舌暗红苔薄白，脉弦涩。</p>
          <p>请写出：病位、毛病、宝贝、坏蛋、生成链、辨证结论。</p>

          <blockquote>
            <p>
              <strong>核心心法：</strong>辨证就像破案，看似神秘，实则有理可循。掌握了"收集线索→定位房间→判断毛病→揪出坏蛋→生成辨证链"这五个步骤，你就拥有了中医诊断的"侦探思维"。多用、多练、多思考，你将越来越熟练。记住：每一次辨证，都是在为病人的健康"破案"。
            </p>
          </blockquote>
        </section>
      </div>
    </div>
  )
}