import SectionImage from '../components/SectionImage'

export default function Module4() {
  return (
    <div className="page-enter-active">
      <div className="text-center mb-12">
        <span className="text-5xl">🦠</span>
        <h1 className="font-serif text-3xl sm:text-4xl font-bold text-ink-700 mt-4 mb-2">
          模块四：谁在捣乱？——认识病因
        </h1>
        <div className="decorative-line mx-auto" />
        <p className="text-ink-500 text-lg">
          身体好好的，为什么会生病？——来认识一下那些捣乱的"坏蛋"
        </p>
      </div>

      <SectionImage
        prompt="Six symbolic elements floating in a mystical environment, wind swirls, ice crystals, summer sun, water droplets, dry autumn leaves, fire flames, arranged in a circle, ethereal glowing atmosphere, soft pastel colors with warm amber light"
        alt="中医病因"
      />

      <div className="content-section">
        {/* ========== sec-m4-1: 六淫 ========== */}
        <section id="sec-m4-1">
          <h2>一、外来的六大坏蛋（六淫）</h2>
          <p>
            生活中，我们的身体随时都可能受到外界"坏蛋"的入侵。古人总结出了六种最常见的"外来坏蛋"——<strong>风、寒、暑、湿、燥、火</strong>，合称<strong>"六淫"</strong>。"淫"就是太过分的意思——这些自然界的正常气候，一旦"过分"了，就会变成伤害身体的邪气。
          </p>
          <p>
            把这六个坏蛋想象成六个不同风格的小偷或破坏者，认识它们的作案手法，才能有效防范。
          </p>

          <h3>🌬️ 风——乱窜的小偷</h3>
          <p>
            <strong>风邪</strong>的性格就像一个小偷——它<strong>来无影去无踪</strong>，专门钻空子。风是六淫中的"带头大哥"，最容易和其他坏蛋联手作案，形成<strong>风寒、风热、风湿</strong>等组合。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>善行数变</strong></td>
                <td>到处乱窜，变化快</td>
                <td>疼痛位置游走不定（一会儿肩膀疼、一会儿膝盖疼）、起病急、变化快（荨麻疹此起彼伏）</td>
              </tr>
              <tr>
                <td><strong>开泄</strong></td>
                <td>钻空子，打开毛孔</td>
                <td>出汗、怕风、毛孔张开——就像小偷撬开了门窗</td>
              </tr>
              <tr>
                <td><strong>易袭阳位</strong></td>
                <td>喜欢攻击上半身</td>
                <td>头痛、鼻塞、咽喉痒、脖子僵硬——风最喜欢往"高处"跑</td>
              </tr>
            </tbody>
          </table>
          <p>
            风邪最常见的搭档：<strong>风寒</strong>（怕冷重、不出汗）、<strong>风热</strong>（发热重、喉咙痛）、<strong>风湿</strong>（关节酸痛沉重）。防风的关键是保护好脖子和后脑勺——特别是出汗后不要吹风。
          </p>

          <h3>❄️ 寒——让一切结冰</h3>
          <p>
            <strong>寒邪</strong>就像冬天里的寒流——它走到哪里，哪里就<strong>冻住</strong>。寒邪最伤人阳气，是最阴冷的坏蛋。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>收引</strong></td>
                <td>收缩、收紧</td>
                <td>血管收缩→面色苍白；毛孔收缩→不出汗；筋脉收缩→手脚冰冷、抽筋、关节屈伸不利</td>
              </tr>
              <tr>
                <td><strong>凝滞</strong></td>
                <td>冻住、凝固</td>
                <td>气血被"冻住"运行不畅→剧烈疼痛（得热痛减、遇冷加重）。中医说"不通则痛"</td>
              </tr>
              <tr>
                <td><strong>伤阳气</strong></td>
                <td>灭火降温</td>
                <td>怕冷、手足不温、精神萎靡、大便稀溏、小便清长。就像房子里的暖气被关掉了</td>
              </tr>
            </tbody>
          </table>
          <p>
            防寒最重要的是保暖——尤其是腹部、腰部和脚底。寒从脚底生，脚暖了全身就暖了。冬天喝姜茶、热水泡脚都是驱寒的好办法。
          </p>

          <h3>☀️ 暑——桑拿天</h3>
          <p>
            <strong>暑邪</strong>只在夏天出现，是<strong>热 + 湿</strong>的复合型邪气。暑邪就像盛夏的桑拿天——又热又闷，让人透不过气来。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>热</strong></td>
                <td>炎热炙烤</td>
                <td>高烧、面红、口渴、大汗——身体像被放在火上烤</td>
              </tr>
              <tr>
                <td><strong>湿</strong></td>
                <td>闷热潮湿</td>
                <td>身体沉重、头重如裹、胸闷恶心、食欲不振——又热又闷，像蒸桑拿</td>
              </tr>
              <tr>
                <td><strong>耗气伤津</strong></td>
                <td>消耗能量和水分</td>
                <td>大汗淋漓后乏力、气短、口干、小便少——身体像被太阳晒干的毛巾</td>
              </tr>
            </tbody>
          </table>
          <p>
            中暑分为两种：<strong>阳暑</strong>（在烈日下暴晒导致——高烧、大汗、口渴、头晕）和<strong>阴暑</strong>（贪凉导致——怕冷、恶心、腹胀、腹泻）。防暑要注意：避免暴晒，及时补充水分（最好是淡盐水），空调不要开太低，室内外温差不宜过大。
          </p>

          <h3>💧 湿——屋里返潮</h3>
          <p>
            <strong>湿邪</strong>就像回南天里墙上的水珠——<strong>黏黏糊糊、沉重不爽</strong>。湿邪是最"黏人"的坏蛋，一旦被它缠上，很难甩掉。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>重浊</strong></td>
                <td>沉重、污浊</td>
                <td>头重如裹、身体困重、四肢酸懒、像灌了铅一样；分泌物秽浊（眼屎多、白带多、大便黏腻冲不干净）</td>
              </tr>
              <tr>
                <td><strong>黏滞</strong></td>
                <td>黏腻、滞涩</td>
                <td>病程长、缠绵难愈——湿气重的病特别难好；舌苔厚腻、口中黏腻、大便黏马桶</td>
              </tr>
              <tr>
                <td><strong>趋下</strong></td>
                <td>往下走</td>
                <td>湿邪喜欢攻击下半身：下肢水肿、脚气、白带多、小便浑浊、大便稀溏。就像水往低处流</td>
              </tr>
              <tr>
                <td><strong>困脾</strong></td>
                <td>影响消化系统</td>
                <td>食欲不振、腹胀、大便稀溏——脾"被困住了"，运化功能下降。脾喜燥恶湿，湿气最伤脾</td>
              </tr>
            </tbody>
          </table>
          <p>
            祛湿的要点：少吃甜食、油腻和生冷食物（这些最容易生湿）；多吃薏米、赤小豆、冬瓜、茯苓等祛湿食材；适当运动出汗是最好的"除湿机"。
          </p>

          <h3>🍂 燥——秋燥干裂</h3>
          <p>
            <strong>燥邪</strong>就像秋天的空气——<strong>干！</strong>它专门抢夺身体里的水分，最受害的是<strong>肺</strong>和<strong>皮肤</strong>。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>干涩</strong></td>
                <td>干燥枯涩</td>
                <td>口干舌燥、鼻干咽干、眼睛干涩、皮肤干裂起皮、大便干结、小便短少——全身像被抽干了水分</td>
              </tr>
              <tr>
                <td><strong>伤肺</strong></td>
                <td>肺最怕燥</td>
                <td>干咳无痰或痰少黏稠、不易咳出、喉咙痒痛、鼻出血——肺喜润恶燥，燥邪最伤肺</td>
              </tr>
            </tbody>
          </table>
          <p>
            燥邪分两种：<strong>温燥</strong>（初秋——偏热，伴有发热、咽痛）和<strong>凉燥</strong>（深秋——偏寒，伴有怕冷、鼻塞）。防燥吃梨、百合、银耳、蜂蜜、莲藕等润肺生津的食物；秋天要多喝水，室内可以放加湿器。
          </p>

          <h3>🔥 火/热——火灾现场</h3>
          <p>
            <strong>火热之邪</strong>是六淫中最"猛"的坏蛋——它就像一场<strong>火灾</strong>，所到之处一片焦土。火和热本质相同，只是程度不同——热是火之渐，火是热之极。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>炎上</strong></td>
                <td>火苗往上窜</td>
                <td>头痛、面红、目赤、牙龈肿痛、口舌生疮——火喜欢"上头"，头面部症状最明显</td>
              </tr>
              <tr>
                <td><strong>迫血</strong></td>
                <td>逼迫血液乱跑</td>
                <td>各种出血：鼻血、牙龈出血、皮下紫斑、月经过多——"热迫血妄行"，火把血液烧得乱窜</td>
              </tr>
              <tr>
                <td><strong>扰神</strong></td>
                <td>扰乱心神</td>
                <td>心烦失眠、狂躁不安、神志不清、说胡话——"火扰心神"，心神被火烧得不得安宁</td>
              </tr>
              <tr>
                <td><strong>耗气伤津</strong></td>
                <td>烧干水分和能量</td>
                <td>口渴多饮、小便短赤、大便干结、乏力——火把身体里的水和能量都烧干了</td>
              </tr>
            </tbody>
          </table>
          <p>
            火还分<strong>实火</strong>和<strong>虚火</strong>：实火是真正的"火灾"——来得猛、症状重、需要灭火（清热泻火）；虚火是"炉子没水干烧"——阴虚导致火旺、症状较轻但缠绵、需要滋阴降火。实火吃苦瓜、黄连、金银花；虚火吃银耳、麦冬、知母。
          </p>

          <h3>六淫小结表格</h3>
          <div className="overflow-x-auto">
            <table>
              <thead>
                <tr>
                  <th>六淫</th>
                  <th>生活比喻</th>
                  <th>主要特性</th>
                  <th>最爱攻击</th>
                  <th>典型表现</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>风</strong></td>
                  <td>乱窜的小偷</td>
                  <td>善行数变、开泄</td>
                  <td>上半身、皮肤</td>
                  <td>游走性疼痛、怕风、出汗、起病急</td>
                </tr>
                <tr>
                  <td><strong>寒</strong></td>
                  <td>让一切结冰</td>
                  <td>收引、凝滞、伤阳</td>
                  <td>筋骨、腹部</td>
                  <td>剧烈冷痛、怕冷、不出汗、手足冰冷</td>
                </tr>
                <tr>
                  <td><strong>暑</strong></td>
                  <td>桑拿天</td>
                  <td>热、湿、耗气伤津</td>
                  <td>全身气津</td>
                  <td>高热、大汗、口渴、乏力、胸闷恶心</td>
                </tr>
                <tr>
                  <td><strong>湿</strong></td>
                  <td>屋里返潮</td>
                  <td>重浊、黏滞、趋下、困脾</td>
                  <td>下半身、脾</td>
                  <td>身体沉重、舌苔厚腻、大便黏腻、病程长</td>
                </tr>
                <tr>
                  <td><strong>燥</strong></td>
                  <td>秋燥干裂</td>
                  <td>干涩、伤肺</td>
                  <td>肺、皮肤、孔窍</td>
                  <td>口干鼻干、干咳少痰、皮肤干裂</td>
                </tr>
                <tr>
                  <td><strong>火/热</strong></td>
                  <td>火灾现场</td>
                  <td>炎上、迫血、扰神、耗津</td>
                  <td>头面、心、血</td>
                  <td>面红目赤、口舌生疮、出血、心烦失眠</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* ========== sec-m4-2: 内邪 ========== */}
        <section id="sec-m4-2">
          <h2>二、家里自己生的麻烦（内邪）</h2>
          <p>
            除了从外面来的"六淫"坏蛋，很多时候病邪是<strong>身体内部自己产生</strong>的。就像一栋房子，外面虽然有坏人，但很多问题其实是内部水管老化、垃圾堆积、电线短路造成的。这些"内邪"包括：<strong>痰、饮、瘀血、食积、气滞</strong>。
          </p>

          <h3>🛢️ 痰——下水道油污结块</h3>
          <p>
            <strong>痰</strong>是体内水液代谢异常产生的病理产物。它比湿更浓稠、更黏腻。想象一下厨房下水道里日积月累的<strong>油污结块</strong>——那就是痰！
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>有形之痰</strong></td>
                <td>看得见、咳得出</td>
                <td>咳嗽咳痰（白痰/黄痰/泡沫痰）、喉咙痰鸣</td>
              </tr>
              <tr>
                <td><strong>无形之痰</strong></td>
                <td>看不见、停在各处</td>
                <td>眩晕（痰蒙清窍）、胸闷（痰阻胸膈）、肥胖（痰湿泛溢肌肤）、瘰疬（痰核结聚）、癫痫（痰迷心窍）</td>
              </tr>
              <tr>
                <td><strong>脾为生痰之源</strong></td>
                <td>脾虚是根本原因</td>
                <td>脾运化水液功能下降→水湿聚集→凝结成痰。所以治痰要治脾——"治痰先治脾"</td>
              </tr>
            </tbody>
          </table>
          <p>
            中医有句话叫<strong>"百病皆由痰作祟"</strong>——痰可以停留在全身上下任何一个地方，引起各种奇怪的症状。化痰的关键是健脾祛湿，陈皮、半夏、茯苓都是经典的化痰药。
          </p>

          <h3>🌊 饮——地面积水</h3>
          <p>
            <strong>饮</strong>和痰性质相似，都是水液代谢异常产生的病理产物，但<strong>饮比痰清稀</strong>。痰像下水道的油污结块，饮就像<strong>地上的一滩积水</strong>——清稀、流动性强、停在哪里哪里出问题。
          </p>
          <table>
            <thead>
              <tr>
                <th>部位</th>
                <th>名称</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>停于胸胁</td>
                <td><strong>悬饮</strong></td>
                <td>胸胁胀满、咳嗽时牵引疼痛、呼吸困难——就像水悬在胸胁之间</td>
              </tr>
              <tr>
                <td>停于肺</td>
                <td><strong>支饮</strong></td>
                <td>咳喘、不能平卧、痰液清稀泡沫状——就像水液支撑在肺里</td>
              </tr>
              <tr>
                <td>停于胃肠</td>
                <td><strong>痰饮</strong></td>
                <td>胃中有振水声、恶心呕吐清水、腹部胀满——就像水在胃肠里晃荡</td>
              </tr>
              <tr>
                <td>停于四肢肌肤</td>
                <td><strong>溢饮</strong></td>
                <td>身体沉重、肢体浮肿、小便不利——水液溢到皮肤和四肢</td>
              </tr>
            </tbody>
          </table>
          <p>
            饮和痰的根本原因相同——<strong>肺、脾、肾</strong>三脏功能失调，水液代谢障碍。温化水饮是主要治法，代表方有<strong>苓桂术甘汤</strong>、<strong>小青龙汤</strong>等。
          </p>

          <h3>🩸 瘀血——水管生锈</h3>
          <p>
            <strong>瘀血</strong>是体内血液运行不畅、停滞凝结形成的病理产物。想象一下<strong>生锈的水管</strong>——铁锈堵塞了管道，水流不畅，甚至完全堵死。瘀血就是血管里的"铁锈"。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>刺痛</strong></td>
                <td>像针扎一样痛</td>
                <td>疼痛部位固定不移、夜间加重、按压时更痛——"不通则痛"</td>
              </tr>
              <tr>
                <td><strong>肿块</strong></td>
                <td>瘀血聚集形成块</td>
                <td>体表可见青紫肿块（外伤后）、体内可触及硬块（如肌瘤、囊肿）</td>
              </tr>
              <tr>
                <td><strong>出血</strong></td>
                <td>瘀血导致不正常出血</td>
                <td>血色紫暗有血块、皮肤瘀斑、月经血块多——"瘀血不去，新血不安"</td>
              </tr>
              <tr>
                <td><strong>舌象</strong></td>
                <td>舌头上有瘀斑</td>
                <td>舌质紫暗、舌有瘀斑瘀点、舌下静脉曲张（青紫粗大）——这是判断瘀血的重要指标</td>
              </tr>
            </tbody>
          </table>
          <p>
            瘀血的原因很多：气滞（气不行血）、寒凝（寒凝血瘀）、热灼（热迫血瘀）、外伤（直接伤络）、久病（久病入络）。活血化瘀的代表药有<strong>丹参、川芎、桃仁、红花、当归</strong>等。
          </p>

          <h3>🗑️ 食积——垃圾桶满了</h3>
          <p>
            <strong>食积</strong>就是食物停留在胃肠里消化不了。就像<strong>垃圾桶装满了</strong>，新的垃圾进不去，旧的在里面发酵、发臭。这在小孩子身上最常见——看到好吃的就停不下来，吃多了就出问题。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>胃胀腹胀</strong></td>
                <td>肚子鼓鼓的、按上去不舒服、拍起来像鼓一样响</td>
              </tr>
              <tr>
                <td><strong>打嗝酸腐</strong></td>
                <td>打嗝有酸臭味、像食物馊了的味道——这是因为食物在胃里发酵了</td>
              </tr>
              <tr>
                <td><strong>恶心呕吐</strong></td>
                <td>吐出来的东西有酸腐味、吐完感觉舒服一些</td>
              </tr>
              <tr>
                <td><strong>大便异常</strong></td>
                <td>要么便秘（下不了）、要么腹泻酸臭（强行排泄）、大便中可见未消化的食物</td>
              </tr>
              <tr>
                <td><strong>舌苔厚腻</strong></td>
                <td>舌苔厚厚的、发黄或发白、口中酸臭、食欲不振</td>
              </tr>
            </tbody>
          </table>
          <p>
            消食导滞是治疗食积的根本方法。记住三种"消化酶"——<strong>山楂</strong>消肉食积、<strong>神曲</strong>消米面积、<strong>麦芽</strong>消淀粉积。中成药<strong>保和丸</strong>是消食导滞的代表方。
          </p>

          <h3>🔌 气滞——电线打结</h3>
          <p>
            <strong>气滞</strong>是人体气的运行不畅——该流动的地方堵住了。就像家里的<strong>电线打了结</strong>，电流过不去，该亮的灯不亮，该转的电器不转。
          </p>
          <table>
            <thead>
              <tr>
                <th>特性</th>
                <th>含义</th>
                <th>表现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>胀痛</strong></td>
                <td>胀得难受的痛</td>
                <td>胸胁胀痛、腹部胀满、乳房胀痛——"气不通则胀"</td>
              </tr>
              <tr>
                <td><strong>窜痛</strong></td>
                <td>疼痛跑来跑去</td>
                <td>疼痛位置不固定，一会儿这里痛一会儿那里痛——气在体内乱窜</td>
              </tr>
              <tr>
                <td><strong>嗳气叹息</strong></td>
                <td>打嗝、叹气</td>
                <td>打嗝后感觉舒服一点、动不动就叹气——身体在试图打通"气结"</td>
              </tr>
              <tr>
                <td><strong>情绪相关</strong></td>
                <td>心情不好时加重</td>
                <td>生气、焦虑、抑郁时症状加重——"肝气郁结"是气滞最常见的原因</td>
              </tr>
            </tbody>
          </table>
          <p>
            气滞最常见的原因就是<strong>情绪不畅</strong>——爱生气、爱郁闷的人最容易气滞。气滞的治疗核心是<strong>疏肝理气</strong>，<strong>柴胡、香附、佛手、玫瑰花</strong>都是理气的好选择。中成药<strong>逍遥丸</strong>是疏肝理气的代表方。
          </p>

          <h3>内邪小结表格</h3>
          <div className="overflow-x-auto">
            <table>
              <thead>
                <tr>
                  <th>内邪</th>
                  <th>生活比喻</th>
                  <th>本质</th>
                  <th>核心表现</th>
                  <th>治疗原则</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>痰</strong></td>
                  <td>下水道油污结块</td>
                  <td>水液停聚浓稠</td>
                  <td>咳痰、眩晕、胸闷、肥胖、癫痫</td>
                  <td>健脾化痰</td>
                </tr>
                <tr>
                  <td><strong>饮</strong></td>
                  <td>地面积水</td>
                  <td>水液停聚清稀</td>
                  <td>咳喘不能平卧、浮肿、胃中振水声</td>
                  <td>温化水饮</td>
                </tr>
                <tr>
                  <td><strong>瘀血</strong></td>
                  <td>水管生锈</td>
                  <td>血液停滞凝结</td>
                  <td>刺痛固定、肿块、出血紫暗、舌有瘀斑</td>
                  <td>活血化瘀</td>
                </tr>
                <tr>
                  <td><strong>食积</strong></td>
                  <td>垃圾桶满了</td>
                  <td>食物停滞胃肠</td>
                  <td>胃胀、打嗝酸腐、苔厚腻</td>
                  <td>消食导滞</td>
                </tr>
                <tr>
                  <td><strong>气滞</strong></td>
                  <td>电线打结</td>
                  <td>气行不畅</td>
                  <td>胀痛窜痛、嗳气叹息、情绪相关</td>
                  <td>疏肝理气</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* ========== sec-m4-3: 七情 ========== */}
        <section id="sec-m4-3">
          <h2>三、情绪也是病因（七情）</h2>
          <p>
            中医很早就发现，<strong>情绪</strong>不仅影响心情，还会直接伤害身体。人有七种基本情绪——<strong>喜、怒、忧、思、悲、恐、惊</strong>，合称<strong>"七情"</strong>。正常情况下，这些情绪是正常的心理反应，但如果<strong>过度、过久</strong>，就会变成伤害五脏的"毒药"。
          </p>
          <p>
            七情致病和六淫最大的不同是——六淫从外面来（感冒风寒、中暑等），七情从内部生（生气伤肝、想太多伤脾等）。这也是中医"形神合一"思想的体现——心理和生理是密不可分的。
          </p>

          <h3>😡 怒则气上——伤肝</h3>
          <p>
            发怒时，气会<strong>向上冲</strong>。想象一下一个人暴怒时面红耳赤、青筋暴起的样子——那就是"气上"的表现。
          </p>
          <ul>
            <li><strong>伤肝：</strong>怒伤肝，肝气上逆→头痛、眩晕、面红目赤</li>
            <li><strong>严重时：</strong>肝气上冲太过→呕血（气迫血上行）、晕厥（气上冲脑）</li>
            <li><strong>经典案例：</strong>《三国演义》中周瑜"三气而死"——虽然艺术夸张，但中医认为大怒真的可以致命</li>
          </ul>

          <h3>😄 喜则气缓——伤心</h3>
          <p>
            这里的"喜"不是普通的开心，而是<strong>暴喜、过喜</strong>——高兴过度了。气会<strong>涣散</strong>，就像气球充气太足炸了一样。
          </p>
          <ul>
            <li><strong>伤心：</strong>喜伤心，心气涣散→精神不集中、心慌心悸、失眠</li>
            <li><strong>严重时：</strong>过喜导致心神涣散→狂笑不止、神志失常、甚至猝死</li>
            <li><strong>经典案例：</strong>《儒林外史》中范进中举后喜极而疯——过喜让心神散了</li>
          </ul>

          <h3>🤔 思则气结——伤脾</h3>
          <p>
            <strong>思虑过度</strong>的时候，气会<strong>停滞、打结</strong>。想问题太多、太深，会觉得"气都堵在胸口了"。
          </p>
          <ul>
            <li><strong>伤脾：</strong>思伤脾，脾气郁结→食欲不振、腹胀、消化不良、大便不畅</li>
            <li><strong>严重时：</strong>长期思虑过度→气血生化不足→头晕、乏力、面色萎黄、失眠健忘</li>
            <li><strong>经典案例：</strong>脑力工作者、学生、家庭主妇最容易因思虑过度而伤脾——所谓"积劳成疾"中的"劳"，大半是"思劳"</li>
          </ul>

          <h3>😢 悲则气消——伤肺</h3>
          <p>
            <strong>悲伤</strong>会消耗人体的气。人在大哭之后会感到全身没力气、气短——这就是"气消"的表现。
          </p>
          <ul>
            <li><strong>伤肺：</strong>悲伤肺，肺气消耗→气短乏力、声音低微、容易感冒</li>
            <li><strong>严重时：</strong>长期悲伤→肺气耗竭→呼吸浅促、面色苍白、精神萎靡</li>
            <li><strong>经典案例：</strong>《红楼梦》中林黛玉——长期悲愁，最后肺痨而死。这是典型的"悲则气消"</li>
          </ul>

          <h3>😔 忧则气闭——伤肺</h3>
          <p>
            <strong>忧愁</strong>和悲伤类似，但忧愁的气机变化是"<strong>闭</strong>"——气被堵在里面出不来。就像房间里门窗紧闭，空气不流通。
          </p>
          <ul>
            <li><strong>伤肺：</strong>忧伤肺，肺气郁闭→胸闷、叹气、呼吸不畅、咳嗽</li>
            <li><strong>严重时：</strong>长期忧愁→胸胁胀满、情绪抑郁、失眠多梦</li>
            <li><strong>区别：</strong>悲是"气消"（消耗掉了），忧是"气闭"（堵住了）。悲让人无力，忧让人沉闷</li>
          </ul>

          <h3>😨 恐则气下——伤肾</h3>
          <p>
            <strong>恐惧</strong>时，气会<strong>向下走</strong>。俗语说"吓得屁滚尿流"——这就是恐则气下的最生动描述。气往下走，收不住。
          </p>
          <ul>
            <li><strong>伤肾：</strong>恐伤肾，肾气不固→尿频、尿失禁、遗精、腰膝酸软</li>
            <li><strong>严重时：</strong>极度恐惧→二便失禁、站立不稳、甚至晕厥</li>
            <li><strong>经典案例：</strong>突然被吓到的人会"腿软站不住"——肾主骨，恐伤肾则骨软无力</li>
          </ul>

          <h3>😲 惊则气乱——伤心</h3>
          <p>
            <strong>惊吓</strong>和恐惧不同。惊是<strong>突然的、意外的刺激</strong>，让气<strong>瞬间乱掉</strong>。就像平静的湖面突然被扔进一块大石头——水面瞬间乱了。
          </p>
          <ul>
            <li><strong>伤心：</strong>惊伤心，心气紊乱→心慌心跳加速、惊慌失措、失眠多梦</li>
            <li><strong>严重时：</strong>反复受惊→心胆气虚→容易受惊、胆怯、噩梦连连</li>
            <li><strong>区别：</strong>"恐"是长期的、持续的恐惧；"惊"是突发的外来刺激。惊让人"乱"，恐让人"下"</li>
          </ul>

          <h3>七情小结表格</h3>
          <div className="overflow-x-auto">
            <table>
              <thead>
                <tr>
                  <th>七情</th>
                  <th>气机变化</th>
                  <th>所伤脏腑</th>
                  <th>生活比喻</th>
                  <th>典型表现</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>怒</strong></td>
                  <td>怒则气上</td>
                  <td>肝</td>
                  <td>火山爆发</td>
                  <td>头痛眩晕、面红目赤、血压升高</td>
                </tr>
                <tr>
                  <td><strong>喜</strong></td>
                  <td>喜则气缓</td>
                  <td>心</td>
                  <td>气球充爆</td>
                  <td>心慌、精神不集中、失眠、狂笑</td>
                </tr>
                <tr>
                  <td><strong>思</strong></td>
                  <td>思则气结</td>
                  <td>脾</td>
                  <td>绳子打结</td>
                  <td>食欲不振、腹胀、消化不良</td>
                </tr>
                <tr>
                  <td><strong>悲</strong></td>
                  <td>悲则气消</td>
                  <td>肺</td>
                  <td>漏气的气球</td>
                  <td>气短乏力、声音低微、容易感冒</td>
                </tr>
                <tr>
                  <td><strong>忧</strong></td>
                  <td>忧则气闭</td>
                  <td>肺</td>
                  <td>门窗紧闭</td>
                  <td>胸闷、叹气、呼吸不畅、情绪抑郁</td>
                </tr>
                <tr>
                  <td><strong>恐</strong></td>
                  <td>恐则气下</td>
                  <td>肾</td>
                  <td>电梯急降</td>
                  <td>尿频、尿失禁、腰膝酸软、腿软</td>
                </tr>
                <tr>
                  <td><strong>惊</strong></td>
                  <td>惊则气乱</td>
                  <td>心</td>
                  <td>水面投石</td>
                  <td>心慌、惊慌失措、失眠易惊醒</td>
                </tr>
              </tbody>
            </table>
          </div>

          <blockquote>
            <p>
              <strong>核心心法：</strong>情绪不是"想开点"就能解决的问题——它会真实地伤害你的脏腑。养生的最高境界不是吃什么、练什么，而是<strong>情绪管理</strong>。少生气、少焦虑、少忧愁，就是最好的养生。中医有一句话概括了情绪与健康的关系——<strong>"恬淡虚无，真气从之，精神内守，病安从来"</strong>。
            </p>
          </blockquote>
        </section>
      </div>
    </div>
  )
}