import SectionImage from '../components/SectionImage'

export default function Module3() {
  return (
    <div className="page-enter-active content-section">
      {/* Title */}
      <div className="text-center mb-12">
        <span className="text-5xl">⚠️</span>
        <h1 className="font-serif text-3xl sm:text-4xl font-bold text-ink-700 mt-4 mb-2">
          模块三：家里出的十种乱子——认识状态异常
        </h1>
        <div className="decorative-line mx-auto" />
        <p className="text-ink-500 text-lg">
          辨证的第二步：搞清楚"东西"出了什么毛病
        </p>
      </div>

      {/* Section Image */}
      <SectionImage
        prompt="Abstract visual representation of ten different body conditions, balance and imbalance, warm and cool color contrast, flowing organic shapes, harmonious composition, ethereal healing atmosphere, amber and teal tones"
        alt="十种状态异常"
      />

      {/* ========== sec-m3-1: 不足的毛病（虚） ========== */}
      <section id="sec-m3-1">
        <h2>一、不足的毛病（虚）——家里东西不够用了</h2>
        <p>
          如果说病位是"哪个房间出了问题"，那么状态异常就是"房间里出了什么乱子"。状态异常可以概括为四大类——<strong>不足</strong>、<strong>不通</strong>、<strong>方向反</strong>、<strong>温度不对</strong>，一共十种常见情况。第一类也是最常见的一类：<strong>虚</strong>，就是"不够用了"。
        </p>
        <p>
          "虚"在中医里是最基本的状态异常，指的是身体里的<strong>某种重要物质不足</strong>了。就好比过日子，缺什么都会出乱子——缺电、缺米、缺水、缺暖气、缺自来水、缺存款，每一种不足表现出来的"症状"都不一样。
        </p>

        <h3>六种虚的总结</h3>
        <table>
          <thead>
            <tr>
              <th>类型</th>
              <th>比喻</th>
              <th>原因</th>
              <th>典型表现</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>气虚</strong></td>
              <td>电不足</td>
              <td>过度劳累、久病不愈、脾胃虚弱、营养不良</td>
              <td>乏力懒言、气短自汗、动则加重、面色苍白、舌淡苔白、脉虚无力</td>
            </tr>
            <tr>
              <td><strong>血虚</strong></td>
              <td>米不够</td>
              <td>失血过多、脾胃虚弱生血不足、久病耗伤</td>
              <td>面色萎黄或苍白、头晕眼花、心悸失眠、手足麻木、月经量少色淡、舌淡苔薄、脉细</td>
            </tr>
            <tr>
              <td><strong>阴虚</strong></td>
              <td>冷却水干了</td>
              <td>热病伤阴、久病耗阴、过食辛辣温燥、熬夜</td>
              <td>五心烦热、潮热盗汗、口干咽燥、颧红、舌红少苔或无苔、脉细数</td>
            </tr>
            <tr>
              <td><strong>阳虚</strong></td>
              <td>暖气坏了</td>
              <td>年老体衰、久病伤阳、过食生冷、贪凉受寒</td>
              <td>畏寒怕冷、四肢不温、喜热饮、小便清长、大便稀溏、舌淡胖苔白滑、脉沉迟无力</td>
            </tr>
            <tr>
              <td><strong>津亏</strong></td>
              <td>自来水管干了</td>
              <td>大汗、大吐、大泻、高热伤津、饮水不足</td>
              <td>口燥咽干、皮肤干瘪、尿少便干、眼窝凹陷、舌干少津、脉细数</td>
            </tr>
            <tr>
              <td><strong>精亏</strong></td>
              <td>存折见底了</td>
              <td>先天不足、年老精衰、房劳过度、久病伤精</td>
              <td>发育迟缓、早衰、脱发齿摇、耳鸣耳聋、健忘痴呆、腰膝酸软、男子精少不育、女子经闭不孕</td>
            </tr>
          </tbody>
        </table>

        <h3>虚证的共同特点</h3>
        <p>
          无论哪种虚，都有一些共同的特点：<strong>病程较长</strong>（不是突然发生的）、<strong>体质偏弱</strong>、<strong>喜按喜温</strong>（按着舒服、暖和了舒服）、<strong>脉无力</strong>。用一句话概括：虚证就是"该有的东西不够了"，所以表现以"不足、减退、虚弱"为主。
        </p>
        <p>
          临床上最常见的其实是<strong>多种虚同时存在</strong>，比如<strong>气阴两虚</strong>（又累又渴又出汗）、<strong>气血两虚</strong>（没力气又面黄头晕）、<strong>阴阳两虚</strong>（又怕冷又怕热）。这就像家里同时缺电又缺水，问题就更复杂了。
        </p>
      </section>

      {/* ========== sec-m3-2: 不通的毛病（滞、瘀、停） ========== */}
      <section id="sec-m3-2">
        <h2>二、不通的毛病（滞、瘀、停）——家里的管道堵了</h2>
        <p>
          第二类状态异常是"不够用"的反面——不是少了，而是<strong>堵了</strong>。东西是有的，但是走不动、流通不了。在中医里，最常见的三种"不通"是气滞、血瘀和水停。通俗地说，就是家里的电线打结、水管生锈、地下室积水。
        </p>

        <h3>气滞——电线打结了</h3>
        <p>
          气是能量，应该在身体里顺畅地流动。如果气流动不畅，就像家里的电线被打了结——电器还能用，但时好时坏，还发出异响。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>电线打结——电流能过，但不顺畅</td>
            </tr>
            <tr>
              <td><strong>核心感觉</strong></td>
              <td><strong>胀痛、窜痛</strong>——痛的位置不固定，到处跑；叹气、打嗝、放屁后会舒服一些</td>
            </tr>
            <tr>
              <td><strong>常见部位</strong></td>
              <td>胸胁（乳房胀痛）、腹部（腹胀腹痛）、咽喉（梅核气——喉咙里像有东西堵着，吞不下吐不出）</td>
            </tr>
            <tr>
              <td><strong>典型表现</strong></td>
              <td>情绪波动时加重、爱叹气、胸闷、胁肋胀痛、嗳气、脉弦</td>
            </tr>
          </tbody>
        </table>

        <h3>血瘀——水管生锈了</h3>
        <p>
          血应该在脉管里顺畅地流动。如果血行不畅或者有瘀血停滞，就像水管里生了锈、有了水垢——水流变慢，锈迹斑斑。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>水管生锈——水流不顺畅，内壁粗糙</td>
            </tr>
            <tr>
              <td><strong>核心感觉</strong></td>
              <td><strong>刺痛、固定不移</strong>——痛的位置固定不移，像针扎一样，夜间加重</td>
            </tr>
            <tr>
              <td><strong>典型外观</strong></td>
              <td><strong>舌紫暗或有瘀点瘀斑</strong>、面色晦暗、口唇青紫、肌肤甲错（皮肤干燥粗糙像鱼鳞）、皮下瘀斑</td>
            </tr>
            <tr>
              <td><strong>典型表现</strong></td>
              <td>疼痛固定不移（刺痛）、肿块（质硬、固定）、出血（血色暗紫有血块）、脉涩</td>
            </tr>
          </tbody>
        </table>

        <h3>水停——地下室积水了</h3>
        <p>
          身体的正常水液代谢出了问题，水液停在某个地方排不出去，就像家里的地下室积水了——潮湿、沉重、难受。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>地下室积水——水排不出去，到处湿漉漉</td>
            </tr>
            <tr>
              <td><strong>核心感觉</strong></td>
              <td><strong>头重身沉、四肢困重</strong>——像裹了湿毛巾一样沉重、不清爽</td>
            </tr>
            <tr>
              <td><strong>典型外观</strong></td>
              <td><strong>舌苔腻</strong>（白腻或黄腻）、舌体胖大边有齿痕、面部或下肢浮肿</td>
            </tr>
            <tr>
              <td><strong>典型表现</strong></td>
              <td>水肿（按之凹陷）、头重如裹、胸闷脘痞、大便黏滞不爽、小便不利、带下增多、脉濡或滑</td>
            </tr>
          </tbody>
        </table>

        <h3>三种"不通"的区分表</h3>
        <table>
          <thead>
            <tr>
              <th>对比维度</th>
              <th>气滞</th>
              <th>血瘀</th>
              <th>水停</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>电线打结</td>
              <td>水管生锈</td>
              <td>地下室积水</td>
            </tr>
            <tr>
              <td><strong>疼痛特点</strong></td>
              <td>胀痛、窜痛</td>
              <td>刺痛、固定不移</td>
              <td>重痛、酸痛</td>
            </tr>
            <tr>
              <td><strong>加重因素</strong></td>
              <td>情绪波动</td>
              <td>夜间加重</td>
              <td>阴雨天加重</td>
            </tr>
            <tr>
              <td><strong>减轻因素</strong></td>
              <td>叹气、排气后缓解</td>
              <td>活动后稍减</td>
              <td>出汗、利尿后缓解</td>
            </tr>
            <tr>
              <td><strong>舌象特征</strong></td>
              <td>舌象可正常或略暗</td>
              <td>舌紫暗有瘀点瘀斑</td>
              <td>舌胖大边齿痕、苔腻</td>
            </tr>
            <tr>
              <td><strong>脉象</strong></td>
              <td>弦脉</td>
              <td>涩脉</td>
              <td>濡脉或滑脉</td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* ========== sec-m3-3: 方向反的毛病（逆、陷、脱） ========== */}
      <section id="sec-m3-3">
        <h2>三、方向反的毛病（逆、陷、脱）——东西走错方向了</h2>
        <p>
          身体里的能量和物质本来有固定的运行方向——该上升的上升，该下降的下降。如果方向搞反了，就会出乱子。这就好比家里的下水道反味、吊灯掉下来、大坝决堤——三种情况，一种比一种严重。
        </p>

        <h3>气逆——下水道反味了</h3>
        <p>
          气正常的运行方向是：清气上升、浊气下降。如果气走反了方向——该下降的不降反升，就是"气逆"。就像厨房的下水道反味——脏东西往上涌。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>下水道反味——该下去的往上涌</td>
            </tr>
            <tr>
              <td><strong>常见部位</strong></td>
              <td>胃气上逆→打嗝、反酸、恶心、呕吐；肺气上逆→咳嗽、气喘；肝气上逆→头痛、眩晕、面红目赤</td>
            </tr>
            <tr>
              <td><strong>典型表现</strong></td>
              <td>嗳气呃逆、恶心呕吐、反酸烧心、咳嗽气喘、头痛眩晕、面红目赤、脉弦或滑</td>
            </tr>
            <tr>
              <td><strong>常见原因</strong></td>
              <td>饮食不节（吃太饱、太快）、情绪激动（大怒伤肝）、外邪犯肺（感冒咳嗽）</td>
            </tr>
          </tbody>
        </table>

        <h3>气陷——吊灯掉下来了</h3>
        <p>
          气除了推动和温煦，还有一个重要作用是"升举"——把内脏固定在应有的位置。如果气虚得太厉害，升举无力，内脏就会往下掉，就像吊灯的绳子松了、吊灯掉下来了。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>吊灯掉下来——该在上面待着的掉下来了</td>
            </tr>
            <tr>
              <td><strong>核心表现</strong></td>
              <td><strong>内脏下垂</strong>——胃下垂、脱肛（直肠下垂）、子宫脱垂、肾下垂；<strong>久泻久痢</strong>——拉肚子拉了很久，怎么都止不住</td>
            </tr>
            <tr>
              <td><strong>伴随症状</strong></td>
              <td>气短乏力（气虚的基础表现）、头晕眼花（清气不上升）、腹部坠胀感、舌淡苔白、脉虚无力</td>
            </tr>
            <tr>
              <td><strong>常见原因</strong></td>
              <td>久病气虚、年老体弱、过度劳累、产后失养、长期腹泻耗气</td>
            </tr>
          </tbody>
        </table>
        <p>
          气陷本质上是<strong>气虚的一种特殊表现</strong>——气虚到了"托不住"的程度，内脏就开始往下掉。所以治疗气陷不光要补气，还要"升提"（把掉下来的东西提上去）。
        </p>

        <h3>气脱——大坝决堤了</h3>
        <p>
          气脱是最危急的状态——气在短时间内大量流失，就像大坝决了堤，水一泻千里。这是<strong>危重证候</strong>，常见于大出血、大汗、剧烈呕吐腹泻、中毒、休克等急症。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>大坝决堤——气一下子全跑光了</td>
            </tr>
            <tr>
              <td><strong>核心表现</strong></td>
              <td><strong>大汗淋漓</strong>（冷汗、全身湿透）、<strong>四肢冰冷</strong>（手脚冰凉到手肘膝盖）、<strong>脉微欲绝</strong>（脉搏几乎摸不到）</td>
            </tr>
            <tr>
              <td><strong>伴随症状</strong></td>
              <td>呼吸微弱、面色苍白、神志模糊甚至昏迷、口开目合、手撒遗尿</td>
            </tr>
            <tr>
              <td><strong>常见原因</strong></td>
              <td>大出血、剧烈吐泻、大汗不止、严重外伤、久病正气耗竭</td>
            </tr>
          </tbody>
        </table>
        <p>
          <strong>气脱 vs 气陷：</strong>两者都是气的严重不足，但气陷是"慢慢往下掉"（慢性过程），气脱是"一下子全跑光"（急性过程）。气脱是急危重症，需要紧急抢救。
        </p>
      </section>

      {/* ========== sec-m3-4: 温度不对的毛病（寒、热） ========== */}
      <section id="sec-m3-4">
        <h2>四、温度不对的毛病（寒、热）——家里太冷或太热了</h2>
        <p>
          身体有正常的温度范围。如果偏离了这个范围，就是"寒"或"热"的问题。寒就是太冷了，热就是太热了。但问题没那么简单——有时候外表看起来热，里面其实是寒的；有时候外表看起来寒，里面却是热的。这就是中医讲的"真假寒热"。
        </p>

        <h3>寒——水管冻住了</h3>
        <p>
          寒证的本质是<strong>热量不足</strong>，就像冬天水管被冻住了一样——一切都凝固了、停滞了。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>水管冻住——冷得缩成一团，动不了</td>
            </tr>
            <tr>
              <td><strong>核心表现</strong></td>
              <td><strong>怕冷</strong>（得热减轻）、<strong>疼痛</strong>（冷痛、得温痛减）、口不渴或喜热饮、面色白、四肢冷</td>
            </tr>
            <tr>
              <td><strong>分泌物/排泄物</strong></td>
              <td>痰涕清稀、小便清长、大便稀溏</td>
            </tr>
            <tr>
              <td><strong>舌脉</strong></td>
              <td>舌淡苔白滑、脉紧或迟</td>
            </tr>
          </tbody>
        </table>
        <p>
          寒证可分为<strong>表寒</strong>（风寒感冒——怕冷、发热、无汗、头身痛）和<strong>里寒</strong>（脾胃虚寒——肚子冷痛、吃凉的拉肚子）。也可以分为<strong>实寒</strong>（外寒入侵——来得快、程度重）和<strong>虚寒</strong>（阳气不足——来得慢、伴全身虚弱）。
        </p>

        <h3>热——房子着火了</h3>
        <p>
          热证的本质是<strong>热量过剩</strong>，就像房子里着了火——到处是热气腾腾的。
        </p>
        <table>
          <thead>
            <tr>
              <th>维度</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>比喻</strong></td>
              <td>房子着火——热得烧起来了</td>
            </tr>
            <tr>
              <td><strong>核心表现</strong></td>
              <td><strong>发热</strong>（体温升高或自觉发热）、<strong>口渴喜冷饮</strong>、面红目赤、烦躁不安</td>
            </tr>
            <tr>
              <td><strong>分泌物/排泄物</strong></td>
              <td>痰涕黄稠、小便短黄、大便干结或黄臭</td>
            </tr>
            <tr>
              <td><strong>舌脉</strong></td>
              <td>舌红苔黄、脉数（快）</td>
            </tr>
          </tbody>
        </table>
        <p>
          热证也可分为<strong>表热</strong>（风热感冒——发热重、怕冷轻、咽痛、黄涕）和<strong>里热</strong>（胃火——牙龈肿痛、口臭、便秘；肝火——头痛、眼红、脾气暴躁）。
        </p>

        <h3>真假寒热——现象不等于本质</h3>
        <p>
          这是中医辨证中最精妙也最容易搞错的地方——有些人看起来热，其实是寒；有些人看起来寒，其实是热。<strong>不能只看表面现象，必须透过现象看本质。</strong>
        </p>

        <h4>真热假寒——热到极致反似寒</h4>
        <p>
          体内有真热（内热极重），但四肢末端却冰冷。这是因为热得太厉害，把气堵在了体内，气到不了四肢末端。就像暖气烧得太旺，管道堵了，散热片反而是凉的。
        </p>
        <table>
          <thead>
            <tr>
              <th>症状</th>
              <th>看似"寒"</th>
              <th>实为"热"（看本质）</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>四肢</strong></td>
              <td>手足冰冷</td>
              <td>胸腹灼热烫手</td>
            </tr>
            <tr>
              <td><strong>口渴</strong></td>
              <td>—</td>
              <td>口渴喜冷饮、甚至想喝冰水</td>
            </tr>
            <tr>
              <td><strong>舌象</strong></td>
              <td>—</td>
              <td>舌红苔黄燥（本质是热的）</td>
            </tr>
            <tr>
              <td><strong>脉象</strong></td>
              <td>脉沉（表面是沉的）</td>
              <td>沉而有力、沉而数（按到底是有力的、快的）</td>
            </tr>
            <tr>
              <td><strong>二便</strong></td>
              <td>—</td>
              <td>小便短赤、大便秘结</td>
            </tr>
          </tbody>
        </table>

        <h4>真寒假热——寒到极致反似热</h4>
        <p>
          体内有真寒（阳气极虚），但脸上却发红发热。这是因为寒得太厉害，虚阳被逼浮到表面。就像冬天最冷的时候，地下水反而是热的——表面现象和内在本质完全相反。
        </p>
        <table>
          <thead>
            <tr>
              <th>症状</th>
              <th>看似"热"</th>
              <th>实为"寒"（看本质）</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>面色</strong></td>
              <td>面红</td>
              <td>颧红如妆（像涂了胭脂，红色浮在表面）</td>
            </tr>
            <tr>
              <td><strong>口渴</strong></td>
              <td>口渴</td>
              <td>渴但不欲饮，或只想喝少量热水</td>
            </tr>
            <tr>
              <td><strong>舌象</strong></td>
              <td>—</td>
              <td>舌淡苔白滑（本质是寒的）</td>
            </tr>
            <tr>
              <td><strong>脉象</strong></td>
              <td>脉大（表面浮大）</td>
              <td>大而无力、按之欲散（按到底是空的、没力的）</td>
            </tr>
            <tr>
              <td><strong>身热</strong></td>
              <td>自觉发热</td>
              <td>想盖被子、想靠近热源</td>
            </tr>
          </tbody>
        </table>

        <h3>寒热辨证口诀</h3>
        <blockquote>
          <p>
            寒热辨证并不难，抓住本质是关键。<br />
            口渴饮水辨寒热，喜冷喜热分真假。<br />
            舌脉从来不说谎，红黄为热淡白寒。<br />
            数脉为热迟脉寒，有力无力辨虚实。
          </p>
        </blockquote>
      </section>

      {/* Bottom summary */}
      <div className="mt-16 pt-8 border-t border-ink-200">
        <h2 className="text-2xl font-bold text-ink-700">十种乱子速记</h2>
        <table>
          <thead>
            <tr>
              <th>大类</th>
              <th>具体类型</th>
              <th>核心比喻</th>
              <th>关键词</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td rowSpan={6}><strong>不足（虚）</strong></td>
              <td>气虚</td>
              <td>电不足</td>
              <td>乏力、气短、自汗</td>
            </tr>
            <tr>
              <td>血虚</td>
              <td>米不够</td>
              <td>面白、头晕、心悸</td>
            </tr>
            <tr>
              <td>阴虚</td>
              <td>冷却水干了</td>
              <td>五心烦热、盗汗、舌红少苔</td>
            </tr>
            <tr>
              <td>阳虚</td>
              <td>暖气坏了</td>
              <td>怕冷、四肢凉、喜热饮</td>
            </tr>
            <tr>
              <td>津亏</td>
              <td>自来水干了</td>
              <td>口干、皮肤干、尿少</td>
            </tr>
            <tr>
              <td>精亏</td>
              <td>存折见底了</td>
              <td>早衰、发育迟缓、腰膝酸软</td>
            </tr>
            <tr>
              <td rowSpan={3}><strong>不通（滞瘀停）</strong></td>
              <td>气滞</td>
              <td>电线打结</td>
              <td>胀痛、窜痛、叹气</td>
            </tr>
            <tr>
              <td>血瘀</td>
              <td>水管生锈</td>
              <td>刺痛、固定、舌紫暗</td>
            </tr>
            <tr>
              <td>水停</td>
              <td>地下室积水</td>
              <td>头重、身沉、苔腻</td>
            </tr>
            <tr>
              <td rowSpan={3}><strong>方向反（逆陷脱）</strong></td>
              <td>气逆</td>
              <td>下水道反味</td>
              <td>打嗝、反酸、咳嗽</td>
            </tr>
            <tr>
              <td>气陷</td>
              <td>吊灯掉下来</td>
              <td>内脏下垂、久泻</td>
            </tr>
            <tr>
              <td>气脱</td>
              <td>大坝决堤</td>
              <td>大汗、肢冷、脉微</td>
            </tr>
            <tr>
              <td rowSpan={2}><strong>温度不对</strong></td>
              <td>寒</td>
              <td>水管冻住</td>
              <td>怕冷、冷痛、得热减轻</td>
            </tr>
            <tr>
              <td>热</td>
              <td>房子着火</td>
              <td>发热、口渴、喜冷饮</td>
            </tr>
          </tbody>
        </table>
        <p className="text-center text-ink-500 mt-6">
          十种乱子，其实就是身体的"四类故障"——不够了、堵了、方向反了、温度不对了。掌握这十种状态，辨证已经会了一半。
        </p>
      </div>
    </div>
  )
}